// ignore_for_file: public_member_api_docs, sort_constructors_first
class UposhakhaModel {
  static var datalist = [
    {"Sl": 1, "BranchName": "Sorail Upzilla Uposhakha", "Code": 1},
    {"Sl": 2, "BranchName": "Kawtali Uposhakha  Brahmanbaria", "Code": 2},
    {"Sl": 3, "BranchName": "Sarak Bazar Uposhakha Brahmanbaria", "Code": 3},
    {"Sl": 4, "BranchName": "Nandanpur Uposhakha Brahmanbaria", "Code": 4},
    {"Sl": 5, "BranchName": "Nasirnagar Uposhakha Brahmanbaria", "Code": 5},
    {"Sl": 6, "BranchName": "Nobinagar Uposhakha Brahmanbaria", "Code": 6},
    {"Sl": 7, "BranchName": "Biswaroad Point Brahmanbaria", "Code": 7},
    {"Sl": 8, "BranchName": "Fulbaria Brahmanbaria Uposhakha", "Code": 8},
    {"Sl": 9, "BranchName": "Krishnanagar Bazar Uposhakha Bbaria", "Code": 9},
    {"Sl": 10, "BranchName": "Islampur Bazar Upo. Brahmanbaria", "Code": 10},
    {"Sl": 11, "BranchName": "Gas Field Gate  Brahmanbaria", "Code": 11},
    {"Sl": 12, "BranchName": "Bijoynagar Amtoli Bazar", "Code": 12},
    {"Sl": 13, "BranchName": "Ramu Uposhakha Coxs Bazar", "Code": 20},
    {"Sl": 14, "BranchName": "Court Bazar Uposhakha Coxs Bazar", "Code": 21},
    {"Sl": 15, "BranchName": "Eidgah Bazar Uposhakha Coxs Bazar", "Code": 22},
    {"Sl": 16, "BranchName": "Sonar Para Uposhakha Coxs Bazar", "Code": 23},
    {"Sl": 17, "BranchName": "Teknaf Uposhakha Coxs Bazar", "Code": 24},
    {"Sl": 18, "BranchName": "Link Road Coxs Bazar Uposhakha", "Code": 25},
    {"Sl": 19, "BranchName": "Naikhongchari Uposhakha Bandarban", "Code": 26},
    {"Sl": 20, "BranchName": "Hnila Bazar Uposhakha Coxs Bazar", "Code": 27},
    {"Sl": 21, "BranchName": "Shamlapur Bazar Upo Coxs Bazar", "Code": 28},
    {"Sl": 22, "BranchName": "Moricha Uposhakha Coxs Bazar", "Code": 29},
    {"Sl": 23, "BranchName": "Oxygen MoorUposhakha Chattogram", "Code": 30},
    {"Sl": 24, "BranchName": "Kaptai Rastar Matha Uposhakha", "Code": 31},
    {"Sl": 25, "BranchName": "Sharafvata Uposhakha Chattagram", "Code": 32},
    {"Sl": 26, "BranchName": "Marium Nagar Uposhakha Chattogram", "Code": 33},
    {"Sl": 27, "BranchName": "Madunaghat Uposhakha  Chattogram.", "Code": 34},
    {"Sl": 28, "BranchName": "Dovashi Bazar Uposhakha", "Code": 35},
    {"Sl": 29, "BranchName": "Rangunia Uposhakha Chattogram", "Code": 36},
    {"Sl": 30, "BranchName": "Sarkerhat Uposhakha  Chattogram", "Code": 40},
    {"Sl": 31, "BranchName": "Aman Bazar Uposhakha  Chattogram", "Code": 41},
    {"Sl": 32, "BranchName": "Raozan Uposhakha Chattogram", "Code": 42},
    {"Sl": 33, "BranchName": "Gohira Uposhakha Chattogram", "Code": 43},
    {"Sl": 34, "BranchName": "Madanhat Uposhakha Chattrogram", "Code": 44},
    {"Sl": 35, "BranchName": "Katirhat Uposhakha Chattogram", "Code": 45},
    {"Sl": 36, "BranchName": "Chowdhuryhat Uposhakha Chattogram", "Code": 46},
    {"Sl": 37, "BranchName": "Temohoni Bazar Uposhakha Chattogram", "Code": 55},
    {"Sl": 38, "BranchName": "Nazirhat Uposhakha Chattogram", "Code": 56},
    {"Sl": 39, "BranchName": "Boidyer Hat Uposhakha Chattogram", "Code": 57},
    {"Sl": 40, "BranchName": "Noajishpur Uposhakha Chattogram", "Code": 58},
    {"Sl": 41, "BranchName": "Kazirhat Uposhakha Chattogram", "Code": 59},
    {"Sl": 42, "BranchName": "Narayanhat Uposhakha Chattogram", "Code": 60},
    {"Sl": 43, "BranchName": "Choto Kumira Uposhakha Chattogram", "Code": 70},
    {"Sl": 44, "BranchName": "Baro Awlia Uposhakha Chattogram", "Code": 71},
    {"Sl": 45, "BranchName": "Shiberhat Uposhakha Chattogram", "Code": 72},
    {"Sl": 46, "BranchName": "Bhairab Bazar Uposhakha Kishoreganj", "Code": 85},
    {"Sl": 47, "BranchName": "Talshahar Uposhakha Brahmanbaria", "Code": 86},
    {"Sl": 48, "BranchName": "Kamolpur Uposhakha Kishoreganj", "Code": 87},
    {"Sl": 49, "BranchName": "Lalpur Brahmanbaria UPOSHAKHA", "Code": 88},
    {"Sl": 50, "BranchName": "Araisidha Bazar Upo Brahmanbaria", "Code": 89},
    {"Sl": 51, "BranchName": "Reserve Bazar Uposhakha Rangamati", "Code": 105},
    {"Sl": 52, "BranchName": "Debashish Nagor Upo. Rangamati", "Code": 106},
    {"Sl": 53, "BranchName": "Tabalchari Uposhakha Rangamati", "Code": 107},
    {"Sl": 54, "BranchName": "Ranirhat Uposhakha Chattogram", "Code": 108},
    {"Sl": 55, "BranchName": "Dighinala Khagrachhari", "Code": 109},
    {"Sl": 56, "BranchName": "Shantirhat Uposhakha Chattogram", "Code": 115},
    {"Sl": 57, "BranchName": "College Bazar Uposhakha Chattogram", "Code": 116},
    {"Sl": 58, "BranchName": "Rawshanhat Uposhakha Chattogram", "Code": 117},
    {"Sl": 59, "BranchName": "Jaldi Uposhakha Chattogram", "Code": 118},
    {"Sl": 60, "BranchName": "Kala Bibi Dighi Chattogram", "Code": 119},
    {"Sl": 61, "BranchName": "Bailchari Uposhakha Chattogram", "Code": 120},
    {"Sl": 62, "BranchName": "Time Bazar Uposhakha Chattogram", "Code": 121},
    {"Sl": 63, "BranchName": "Rustomhat Uposhakha Chattogram", "Code": 122},
    {"Sl": 64, "BranchName": "Char Patharghata Upo  Chattogram", "Code": 123},
    {
      "Sl": 65,
      "BranchName": "Tantar Bazar Uposhakha Brahmanbaria",
      "Code": 125
    },
    {"Sl": 66, "BranchName": "Kasba Uposhakha Brahmanbaria", "Code": 126},
    {"Sl": 67, "BranchName": "Champaknagar Upo. Brahmanbaria", "Code": 127},
    {"Sl": 68, "BranchName": "Kuti Chowmohani Upo. Brahmanbaria", "Code": 128},
    {"Sl": 69, "BranchName": "Nayanpur Bazar Upo Brahmanbaria", "Code": 129},
    {"Sl": 70, "BranchName": "Bazalia Uposhakha Chattogram", "Code": 136},
    {"Sl": 71, "BranchName": "Komol Munshir Hat Chattogram", "Code": 137},
    {
      "Sl": 72,
      "BranchName": "Adunagar Bazar Uposhakha Chattogram",
      "Code": 138
    },
    {"Sl": 73, "BranchName": "Balaghata Uposhakha Bandarban", "Code": 139},
    {"Sl": 74, "BranchName": "Dohazari Uposhakha Chattogram", "Code": 140},
    {"Sl": 75, "BranchName": "Padua Uposhakha Chattagram", "Code": 141},
    {"Sl": 76, "BranchName": "Fultola Bazar Satkania Chattogram", "Code": 142},
    {"Sl": 77, "BranchName": "Mirzakhil Uposhakha Chattogram", "Code": 143},
    {"Sl": 78, "BranchName": "Chambal Bazar Uposhakha Chattogram", "Code": 144},
    {"Sl": 79, "BranchName": "Gachbaria Uposhakha Chattogram", "Code": 145},
    {"Sl": 80, "BranchName": "Chunti Bazar Uposhakha Chattogram", "Code": 146},
    {"Sl": 81, "BranchName": "Matarbari Moheskhali Coxs Bazar", "Code": 147},
    {"Sl": 82, "BranchName": "Pekua Uposhakha Coxs Bazar", "Code": 148},
    {"Sl": 83, "BranchName": "Napura Uposhakha Chattogram", "Code": 149},
    {"Sl": 84, "BranchName": "Dulahazara Coxs Bazar", "Code": 150},
    {"Sl": 85, "BranchName": "Manu Fakir Bazar Chattogram", "Code": 176},
    {"Sl": 86, "BranchName": "Satghatia Pukur Par Chattogram", "Code": 177},
    {"Sl": 87, "BranchName": "Satkania Uposhakha Chattogram", "Code": 179},
    {"Sl": 88, "BranchName": "Kadamtoli Uposhakha  Sylhet", "Code": 250},
    {"Sl": 89, "BranchName": "Jitu Miah s Point Uposhakha Sylhet", "Code": 251},
    {"Sl": 90, "BranchName": "Pirijpur Uposhakha Sylhet", "Code": 252},
    {"Sl": 91, "BranchName": "Boroikandi Uposhakha Sylhet", "Code": 253},
    {"Sl": 92, "BranchName": "TB Gate Sylhet Uposhakha Sylhet", "Code": 254},
    {"Sl": 93, "BranchName": "Sylhet Station Road  Sylhet", "Code": 255},
    {"Sl": 94, "BranchName": "Gowainghat Bazar Uposhakha Sylhet", "Code": 256},
    {"Sl": 95, "BranchName": "Kanaighat Bazar Uposhakha Sylhet", "Code": 257},
    {"Sl": 96, "BranchName": "Jaflong Uposhakha Sylhet", "Code": 258},
    {"Sl": 97, "BranchName": "Golapganj Sylhet Sylhet", "Code": 259},
    {"Sl": 98, "BranchName": "Tuker Bazar Uposhakha Sylhet", "Code": 260},
    {"Sl": 99, "BranchName": "Modina Market Uposhakha Sylhet", "Code": 261},
    {
      "Sl": 100,
      "BranchName": "Osmani Medical College Road  Sylhet",
      "Code": 262
    },
    {"Sl": 101, "BranchName": "Shamsher NagarUpo. Moulvi Bazar", "Code": 270},
    {
      "Sl": 102,
      "BranchName": "Sarkar Bazar Bus Stand  Moulvibazar",
      "Code": 271
    },
    {"Sl": 103, "BranchName": "Tengra Bazar Moulvibazar", "Code": 272},
    {
      "Sl": 104,
      "BranchName": "Adampur Bazar Uposhakha Moulvibazar",
      "Code": 280
    },
    {"Sl": 105, "BranchName": "Bhoirab Bazar Sreemangal", "Code": 281},
    {"Sl": 106, "BranchName": "Kamalganj Uposhakha Moulvi Bazar", "Code": 282},
    {"Sl": 107, "BranchName": "Shibganj Bazar Uposhakha Sylhet", "Code": 290},
    {"Sl": 108, "BranchName": "Fenchuganj Uposhakha Sylhet", "Code": 291},
    {"Sl": 109, "BranchName": "Lala Bazar Uposhakha  Sylhet", "Code": 292},
    {"Sl": 110, "BranchName": "Shahabazpur Uposhakha MoulviBazar", "Code": 300},
    {"Sl": 111, "BranchName": "Ashirganj Bazar Uposhakha Sylhet", "Code": 301},
    {"Sl": 112, "BranchName": "Majortila Uposhakha Sylhet", "Code": 310},
    {"Sl": 113, "BranchName": "Khasdobir Point Uposhakha Sylhet", "Code": 311},
    {"Sl": 114, "BranchName": "Lama Bazar Uposhakha Sylhet", "Code": 312},
    {"Sl": 115, "BranchName": "Tajpur Uposhakha Sylhet", "Code": 320},
    {"Sl": 116, "BranchName": "Khadimpur Bazar Uposhakha  Sylhet", "Code": 321},
    {"Sl": 117, "BranchName": "Sherpur Sylhet Moulvibazar", "Code": 322},
    {"Sl": 118, "BranchName": "Shahestaganj Bazar Uposhakha", "Code": 325},
    {"Sl": 119, "BranchName": "Olipur Highway Uposhakha", "Code": 326},
    {"Sl": 120, "BranchName": "Chunarughat Uposhakha", "Code": 327},
    {
      "Sl": 121,
      "BranchName": "Court Station Road Uposhakha Habi.",
      "Code": 328
    },
    {"Sl": 122, "BranchName": "Nabiganj Upozilla Habiganj", "Code": 329},
    {"Sl": 123, "BranchName": "Mirpur Bazar Uposhakha Habiganj", "Code": 330},
    {"Sl": 124, "BranchName": "Baniachang Uposhakha Habiganj", "Code": 331},
    {"Sl": 125, "BranchName": "Umednagar Shilpa Elaka  Habiganj", "Code": 332},
    {"Sl": 126, "BranchName": "Aushkandi Uposhakha Habiganj", "Code": 333},
    {"Sl": 127, "BranchName": "Asampara Bazar Uposhakha Habiganj", "Code": 334},
    {"Sl": 128, "BranchName": "Phandauk Bazar Upo. Brahmanbaria", "Code": 335},
    {"Sl": 129, "BranchName": "Noapara Bazar Uposhakha Habiganj", "Code": 336},
    {"Sl": 130, "BranchName": "Montola Bazar Uposhakha Habiganj", "Code": 337},
    {
      "Sl": 131,
      "BranchName": "Dharmaghar Bazar Uposhakha Habiganj",
      "Code": 338
    },
    {"Sl": 132, "BranchName": "Chatian Madhabpur Habiganj", "Code": 339},
    {
      "Sl": 133,
      "BranchName": "Choumuhani Bazar Madhabpur Habiganj",
      "Code": 340
    },
    {"Sl": 134, "BranchName": "Barlekha Uposhakha Moulvibazar", "Code": 345},
    {"Sl": 135, "BranchName": "Kulaura Uposhakha Moulvi Bazar", "Code": 346},
    {"Sl": 136, "BranchName": "Brahman Bazar Upo Moulvi Bazar", "Code": 347},
    {"Sl": 137, "BranchName": "Gabindaganj Sunamganj Uposhakha", "Code": 351},
    {"Sl": 138, "BranchName": "Puran Munsafi Road Upo Habiganj", "Code": 361},
    {"Sl": 139, "BranchName": "Jaintapur Uposhakha Sylhet", "Code": 371},
    {"Sl": 140, "BranchName": "Nathullahbad Uposhakha Barisal", "Code": 400},
    {"Sl": 141, "BranchName": "Rupatali Uposhakha Barisal", "Code": 401},
    {"Sl": 142, "BranchName": "Barishal Bazar Road Uposhakha", "Code": 402},
    {
      "Sl": 143,
      "BranchName": "Barishal Chawk Bazar Upo. Barishal",
      "Code": 403
    },
    {"Sl": 144, "BranchName": "Dhamura Bandar Uposhakha Barishal", "Code": 404},
    {"Sl": 145, "BranchName": "Chowmatha Uposhakha Barishal", "Code": 405},
    {
      "Sl": 146,
      "BranchName": "Kalaya Bandar Uposhakha Patuakhali",
      "Code": 406
    },
    {
      "Sl": 147,
      "BranchName": "Bauphal Bazar Uposhakha Patuakhali",
      "Code": 407
    },
    {"Sl": 148, "BranchName": "Bangla Bazar Barishal Barishal", "Code": 408},
    {"Sl": 149, "BranchName": "Shikarpur Uposhakha Barishal", "Code": 409},
    {
      "Sl": 150,
      "BranchName": "Amtali Chowrasta Uposhakha Barguna",
      "Code": 410
    },
    {"Sl": 151, "BranchName": "Batajor Bazar Barishal Barishal", "Code": 411},
    {"Sl": 152, "BranchName": "Torki Bandar Uposhakha Barishal", "Code": 412},
    {"Sl": 153, "BranchName": "Bakerganj Uposhakha Barishal", "Code": 413},
    {
      "Sl": 154,
      "BranchName": "Kalisuri Bazar Uposhakha Patuakhali",
      "Code": 414
    },
    {"Sl": 155, "BranchName": "Alipur Uposhakha Patuakhali", "Code": 415},
    {"Sl": 156, "BranchName": "Gouranadi Uposhakha Barishal", "Code": 416},
    {"Sl": 157, "BranchName": "Daulatkhan Uposhakha Bhola", "Code": 420},
    {"Sl": 158, "BranchName": "Bhola Banglabazar Uposhakha Bhola", "Code": 421},
    {"Sl": 159, "BranchName": "Poranganj Uposhakha Bhola", "Code": 422},
    {"Sl": 160, "BranchName": "Charfassion Uposhakha Bhola", "Code": 423},
    {"Sl": 161, "BranchName": "Kunjer Hat Uposhakha Bhola", "Code": 424},
    {"Sl": 162, "BranchName": "Rajapur Uposhakha Jhalokathi", "Code": 435},
    {"Sl": 163, "BranchName": "Amua Bazar Uposhakha Jhalokathi", "Code": 436},
    {"Sl": 164, "BranchName": "Pirojpur Sadar Uposhakha Pirojpur", "Code": 437},
    {
      "Sl": 165,
      "BranchName": "Mathbaria Bazar Uposhakha  Pirojpur",
      "Code": 438
    },
    {"Sl": 166, "BranchName": "Kawkhali Pirojpur", "Code": 439},
    {"Sl": 167, "BranchName": "Bamna Uposhakha Barguna", "Code": 440},
    {
      "Sl": 168,
      "BranchName": "Indurkani Bazar Uposhakha Pirojpur",
      "Code": 441
    },
    {"Sl": 169, "BranchName": "Patuakhali Puran Bazar Uposhakha", "Code": 451},
    {"Sl": 170, "BranchName": "Boga Bazar Uposhakha  Patuakhali", "Code": 452},
    {
      "Sl": 171,
      "BranchName": "Tushkhali Bazar Uposhakha  Pirojpur",
      "Code": 461
    },
    {"Sl": 172, "BranchName": "Nirala Uposhakha  Khulna", "Code": 550},
    {"Sl": 173, "BranchName": "Daulatpur Uposhakha Khulna", "Code": 551},
    {"Sl": 174, "BranchName": "Koiya Bazar Uposhakha Khulna", "Code": 552},
    {"Sl": 175, "BranchName": "Batiaghata Uposhakha Khulna", "Code": 553},
    {"Sl": 176, "BranchName": "Dumuria Uposhakha Khulna", "Code": 554},
    {"Sl": 177, "BranchName": "Paikgacha Uposhakha Khulna", "Code": 555},
    {"Sl": 178, "BranchName": "Sener Bazar Uposhakha Khulna", "Code": 556},
    {"Sl": 179, "BranchName": "Rupsha Ghat Uposhakha Khulna", "Code": 557},
    {"Sl": 180, "BranchName": "Keshabpur Bazar Uposhakha Jashore", "Code": 558},
    {"Sl": 181, "BranchName": "Mongla Bazar Uposhakha Bagerhat", "Code": 559},
    {"Sl": 182, "BranchName": "Pulerhat Uposhakha  Jashore", "Code": 560},
    {"Sl": 183, "BranchName": "Palbari Moor Uposhakha  Jashore", "Code": 561},
    {
      "Sl": 184,
      "BranchName": "Monihar Bus Stand Uposhakha Jashore",
      "Code": 562
    },
    {"Sl": 185, "BranchName": "Monirampur Uposhakha Jashore", "Code": 563},
    {
      "Sl": 186,
      "BranchName": "Jashore Kolabagan Uposhakha Jashore",
      "Code": 564
    },
    {"Sl": 187, "BranchName": "Satmail Bazar Uposhakha Jashore", "Code": 565},
    {"Sl": 188, "BranchName": "Narail Sadar Uposhakha Narail", "Code": 566},
    {"Sl": 189, "BranchName": "Chowgacha Bazar Uposhakha Jashore", "Code": 567},
    {"Sl": 190, "BranchName": "Lohagara Bazar Uposhakha Narail", "Code": 568},
    {"Sl": 191, "BranchName": "Langalbandha Uposhakha Jhenaidah", "Code": 569},
    {"Sl": 192, "BranchName": "Chourhash Uposhakha  Kushtia", "Code": 570},
    {"Sl": 193, "BranchName": "Bheramara Uposhakha Kushtia", "Code": 571},
    {"Sl": 194, "BranchName": "Gangni Uposhakha Kushtia", "Code": 572},
    {"Sl": 195, "BranchName": "Meherpur Sadar Meherpur", "Code": 573},
    {"Sl": 196, "BranchName": "Sheikhpara Bazar Jhinaidah", "Code": 574},
    {
      "Sl": 197,
      "BranchName": "Chuadanga Sadar Uposhakha Chuadanga",
      "Code": 575
    },
    {
      "Sl": 198,
      "BranchName": "Panch Raster More Uposhakha Kushtia",
      "Code": 576
    },
    {"Sl": 199, "BranchName": "Kumarkhali Uposhakha Kushtia", "Code": 577},
    {"Sl": 200, "BranchName": "Harinarayanpur Uposhakha Kushtia", "Code": 578},
    {
      "Sl": 201,
      "BranchName": "Sarajganj Bazar Uposhakha Chuadanga",
      "Code": 579
    },
    {"Sl": 202, "BranchName": "Kulia Bazar Uposhakha Satkhira", "Code": 580},
    {
      "Sl": 203,
      "BranchName": "Jhawdanga Bazar Uposhakha Satkhira",
      "Code": 581
    },
    {"Sl": 204, "BranchName": "Patkelghata Uposhakha Satkhira", "Code": 582},
    {"Sl": 205, "BranchName": "Parulia Bazar Uposhakha", "Code": 583},
    {"Sl": 206, "BranchName": "Kalaroa Uposhakha Satkhira", "Code": 584},
    {"Sl": 207, "BranchName": "Brahmarajpur Bazar Upo Satkhira", "Code": 585},
    {"Sl": 208, "BranchName": "Mujgunni Uposhakha Khulna", "Code": 590},
    {
      "Sl": 209,
      "BranchName": "Rupsha Stand Road Uposhakha Khulna",
      "Code": 591
    },
    {
      "Sl": 210,
      "BranchName": "Khulna New Market Uposhakha Khulna",
      "Code": 592
    },
    {
      "Sl": 211,
      "BranchName": "Nurbag Main Road Uposhakha Jashore",
      "Code": 600
    },
    {"Sl": 212, "BranchName": "Basundia More Uposhakha Jashore", "Code": 601},
    {"Sl": 213, "BranchName": "Gobra Bazar Uposhakha Narail", "Code": 602},
    {"Sl": 214, "BranchName": "Vatpara Bazar Uposhakha Jashore", "Code": 603},
    {"Sl": 215, "BranchName": "Nehalpur Bazar Uposhakha Jashore", "Code": 604},
    {"Sl": 216, "BranchName": "Maijpara Bazar Uposhakha Narail", "Code": 605},
    {"Sl": 217, "BranchName": "Mohajan Bazar Uposhakha Narail", "Code": 606},
    {"Sl": 218, "BranchName": "Fultola Bazar Uposhakha  Khulna", "Code": 607},
    {"Sl": 219, "BranchName": "Baganchra Uposhakha Jashore", "Code": 610},
    {"Sl": 220, "BranchName": "Navaron Uposhakha Jashore", "Code": 611},
    {"Sl": 221, "BranchName": "Jhikargacha Uposhakha Jashore", "Code": 612},
    {"Sl": 222, "BranchName": "Bankra Uposhakha Jashore", "Code": 613},
    {"Sl": 223, "BranchName": "Chutipur Bazar Uposhakha Jashore", "Code": 614},
    {"Sl": 224, "BranchName": "Kotchandpur Uposhakha Jhenaidah", "Code": 620},
    {"Sl": 225, "BranchName": "Barobazar Uposhakha Jhenaidah", "Code": 621},
    {"Sl": 226, "BranchName": "Bhatai Bazar Uposhakha Jhenidah", "Code": 622},
    {
      "Sl": 227,
      "BranchName": "Jhenaidah Sadar Uposhakha Jhenaidah",
      "Code": 623
    },
    {
      "Sl": 228,
      "BranchName": "Shailkupa Bazar Uposhakha Jhenaidah",
      "Code": 624
    },
    {"Sl": 229, "BranchName": "Harinakunda Uposhakha Jhenaidah", "Code": 625},
    {"Sl": 230, "BranchName": "Maheshpur Uposhakha Jhenaidah", "Code": 626},
    {"Sl": 231, "BranchName": "Dak Bangla Bazar Jhenaidah", "Code": 627},
    {"Sl": 232, "BranchName": "Hatgopalpur Jhenaidah", "Code": 628},
    {"Sl": 233, "BranchName": "Amla Bazar Uposhakha  Kushtia", "Code": 630},
    {
      "Sl": 234,
      "BranchName": "Trimohoni Bazar Uposhakha  Kushtia",
      "Code": 631
    },
    {"Sl": 235, "BranchName": "Khoksha Uposhakha Kushtia", "Code": 632},
    {"Sl": 236, "BranchName": "Kushtia Mirpur Bazar Kushtia", "Code": 633},
    {"Sl": 237, "BranchName": "Halsha Bazar Uposhakha Kushtia", "Code": 634},
    {"Sl": 238, "BranchName": "Alamdanga Uposhakha Chuadanga", "Code": 635},
    {"Sl": 239, "BranchName": "Khajanagar Bazar Kushtia", "Code": 636},
    {"Sl": 240, "BranchName": "Badhal Bazar Uposhakha Bagerhat", "Code": 640},
    {"Sl": 241, "BranchName": "Jatrapur Uposhakha Bagerhat", "Code": 641},
    {"Sl": 242, "BranchName": "Chitalmari Bazar Bagherhat", "Code": 642},
    {"Sl": 243, "BranchName": "Fakirhat Uposhakha Bagerhat", "Code": 643},
    {"Sl": 244, "BranchName": "Morrelganj Uposhakha", "Code": 644},
    {"Sl": 245, "BranchName": "Foylahat Uposhakha Bagerhat", "Code": 645},
    {"Sl": 246, "BranchName": "Digraj Bagerhat", "Code": 646},
    {"Sl": 247, "BranchName": "Gollamari Uposhakha  Khulna", "Code": 650},
    {"Sl": 248, "BranchName": "Labonchara Bazar Uposhakha Khulna", "Code": 651},
    {
      "Sl": 249,
      "BranchName": "Sheikhpara Power House Upo.  Khulna",
      "Code": 652
    },
    {"Sl": 250, "BranchName": "Boyra Uposhakha Khulna", "Code": 653},
    {"Sl": 251, "BranchName": "Moylapota Uposhakha Khulna", "Code": 654},
    {"Sl": 252, "BranchName": "Sachibunia Bazar Uposhakha Khulna", "Code": 655},
    {"Sl": 253, "BranchName": "Kapilmuni Uposhakha Khulna", "Code": 661},
    {"Sl": 254, "BranchName": "Chuknagar Bazar Uposhakha Khulna", "Code": 662},
    {"Sl": 255, "BranchName": "Fulbari Gate Uposhakha Khulna", "Code": 663},
    {"Sl": 256, "BranchName": "Chalna Bazar Uposhakha Khulna", "Code": 664},
    {"Sl": 257, "BranchName": "Radhanagar Bazar Uposhakha Magura", "Code": 671},
    {
      "Sl": 258,
      "BranchName": "Mohammadpur Magura Uposhakha Magura",
      "Code": 672
    },
    {"Sl": 259, "BranchName": "Jashore University of SciT (JUST)", "Code": 673},
    {"Sl": 260, "BranchName": "Sreepur Magura Uposhakha Magura", "Code": 674},
    {"Sl": 261, "BranchName": "Shimakhali Bazar Uposhakha Magura", "Code": 675},
    {"Sl": 262, "BranchName": "Rupdia Bazar Uposhakha Jashore", "Code": 676},
    {"Sl": 263, "BranchName": "Bagherpara Uposhakha Jashore", "Code": 677},
    {"Sl": 264, "BranchName": "Sachilapur Bazar Uposhakha Magura", "Code": 678},
    {"Sl": 265, "BranchName": "Vaina Moor Uposhakha  Magura", "Code": 679},
    {"Sl": 266, "BranchName": "Nohata Bazar Magura Upo  Magura", "Code": 680},
    {"Sl": 267, "BranchName": "Damurhuda Chuadanga", "Code": 681},
    {"Sl": 268, "BranchName": "Jibonnagar Uposhakha Chuadanga", "Code": 682},
    {"Sl": 269, "BranchName": "Andulbaria Bazar Upo Chuadanga", "Code": 683},
    {"Sl": 270, "BranchName": "Asmankhali Bazar Upo Chuadanga", "Code": 684},
    {"Sl": 271, "BranchName": "Karpashdanga Uposhakha Chuadanga", "Code": 685},
    {
      "Sl": 272,
      "BranchName": "Baradi Bazar Meherpur Upo Meherpur",
      "Code": 686
    },
    {"Sl": 273, "BranchName": "Mujibnagar Uposhakha Meherpur", "Code": 687},
    {"Sl": 274, "BranchName": "Lahini Bottola Uposhakha Kushtia", "Code": 691},
    {"Sl": 275, "BranchName": "Allahar Dorga Uposhakha Kushtia", "Code": 692},
    {"Sl": 276, "BranchName": "Bamundi Uposhakha Meherpur", "Code": 693},
    {
      "Sl": 277,
      "BranchName": "Golapnagar Bazar Uposhakha Kushtia",
      "Code": 694
    },
    {"Sl": 278, "BranchName": "Mahiganj Uposhakha Rangpur", "Code": 700},
    {"Sl": 279, "BranchName": "Medical East Gate Upo. Rangpur", "Code": 701},
    {"Sl": 280, "BranchName": "Dhap Uposhakha Rangpur", "Code": 702},
    {"Sl": 281, "BranchName": "Rangpur Lalbagh Uposhakha Rangpur", "Code": 703},
    {"Sl": 282, "BranchName": "Rangpur Bus Terminal Uposhakha", "Code": 704},
    {"Sl": 283, "BranchName": "Badarganj Uposhakha Rangpur", "Code": 705},
    {"Sl": 284, "BranchName": "Jaldhaka Uposhakha Nilphamari", "Code": 706},
    {
      "Sl": 285,
      "BranchName": "Shathibari Bazar Uposhakha Rangpur",
      "Code": 707
    },
    {"Sl": 286, "BranchName": "Phulbari Kurigram Uposhakha", "Code": 708},
    {"Sl": 287, "BranchName": "Lalmonirhat Sadar Lalmonirhat", "Code": 709},
    {"Sl": 288, "BranchName": "Gobindaganj Gaibandha Uposhakha", "Code": 710},
    {"Sl": 289, "BranchName": "Kurigram Sadar Uposhakha Kurigram", "Code": 711},
    {"Sl": 290, "BranchName": "Bhurungamari Uposhakha Kurigram", "Code": 712},
    {"Sl": 291, "BranchName": "Dimla Uposhakha Nilphamari", "Code": 713},
    {"Sl": 292, "BranchName": "Tushbhandar Uposhakha Lalmonirhat", "Code": 714},
    {
      "Sl": 293,
      "BranchName": "Pirgacha Rangpur Uposhakha Rangpur",
      "Code": 715
    },
    {"Sl": 294, "BranchName": "Saidpur Nilphamari", "Code": 716},
    {"Sl": 295, "BranchName": "Gangachara Uposhakha Rangpur", "Code": 717},
    {"Sl": 296, "BranchName": "Patgram Uposhakha Lalmonirhat", "Code": 718},
    {"Sl": 297, "BranchName": "Nageshwari Uposhakha Kurigram", "Code": 719},
    {"Sl": 298, "BranchName": "Pirganj Rangpur Uposhakha", "Code": 720},
    {"Sl": 299, "BranchName": "Dhaperhat Uposhakha Gaibandha", "Code": 721},
    {"Sl": 300, "BranchName": "Bonarpara Uposhakha Gaibandha", "Code": 722},
    {"Sl": 301, "BranchName": "Mahimaganj Gaibandha", "Code": 723},
    {"Sl": 302, "BranchName": "Sundarganj Uposhakha Gaibandha", "Code": 724},
    {"Sl": 303, "BranchName": "Bahadur Bazar Uposhakha Dinajpur", "Code": 725},
    {"Sl": 304, "BranchName": "Chirirbondor Uposhakha Dinajpur", "Code": 726},
    {"Sl": 305, "BranchName": "Nimnagar Balubari Upo. Dinajpur", "Code": 727},
    {"Sl": 306, "BranchName": "Ranirbandar Uposhakha Dinajpur", "Code": 728},
    {"Sl": 307, "BranchName": "Birampur Uposhakha Dinajpur", "Code": 729},
    {"Sl": 308, "BranchName": "Panchagarh Sadar  Panchagarh", "Code": 730},
    {"Sl": 309, "BranchName": "Birganj Uposhakha Dinajpur", "Code": 731},
    {"Sl": 310, "BranchName": "Boda Bazar Uposhakha Panchagarh", "Code": 732},
    {"Sl": 311, "BranchName": "Atwari Uposhakha Panchagarh", "Code": 733},
    {
      "Sl": 312,
      "BranchName": "Fulbari Dinajpur Uposhakha Dinajpur",
      "Code": 734
    },
    {"Sl": 313, "BranchName": "Nawabganj Dinajpur Uposhakha", "Code": 735},
    {"Sl": 314, "BranchName": "Pirganj Uposhakha Thakurgaon", "Code": 750},
    {"Sl": 315, "BranchName": "Thakurgaon Sadar Thakurgaon", "Code": 751},
    {"Sl": 316, "BranchName": "Ranisankail Uposhakha Thakurgaon", "Code": 752},
    {"Sl": 317, "BranchName": "Thakurgoan Road Uposhakha", "Code": 753},
    {
      "Sl": 318,
      "BranchName": "Nekmarad Bazar Uposhakha Thakurgoan",
      "Code": 754
    },
    {"Sl": 319, "BranchName": "Boro Khochabari  THAKURGAON", "Code": 755},
    {
      "Sl": 320,
      "BranchName": "Jadurani Bazar Uposhakha Thakurgaon",
      "Code": 756
    },
    {"Sl": 321, "BranchName": "Baliadangi Uposhakha Thakurgaon", "Code": 757},
    {"Sl": 322, "BranchName": "Haripur Thakurgoan Upo Thakurgaon", "Code": 758},
    {"Sl": 323, "BranchName": "Bairchuna Uposhakha Thakurgaon", "Code": 759},
    {"Sl": 324, "BranchName": "Dhukurjhari Uposhakha Dinajpur", "Code": 760},
    {"Sl": 325, "BranchName": "Kaharole Uposhakha Dinajpur", "Code": 761},
    {"Sl": 326, "BranchName": "Parbatipur Uposhakha Dinajpur", "Code": 762},
    {"Sl": 327, "BranchName": "Domar Nilphamari", "Code": 771},
    {"Sl": 328, "BranchName": "Ulipur Kurigram", "Code": 772},
    {"Sl": 329, "BranchName": "Paglapir Bazar Uposhakha Rangpur", "Code": 773},
    {"Sl": 330, "BranchName": "Hatibandha Uposhakha Lalmonirhat", "Code": 774},
    {
      "Sl": 331,
      "BranchName": "Kishoreganj Nilphamari  Nilphamari",
      "Code": 775
    },
    {"Sl": 332, "BranchName": "Taraganj Uposhakha Rangpur", "Code": 776},
    {"Sl": 333, "BranchName": "Kaunia Uposhakha  Rangpur", "Code": 777},
    {"Sl": 334, "BranchName": "Honuman Tola Uposhakha  Rangpur", "Code": 778},
    {"Sl": 335, "BranchName": "Panchbibi Uposhakha  Joypurhat", "Code": 850},
    {"Sl": 336, "BranchName": "Akkelpur Uposhakha Joypurhat", "Code": 851},
    {"Sl": 337, "BranchName": "Jamalganj Joypurhat Uposhakha", "Code": 852},
    {"Sl": 338, "BranchName": "Dhamoirhat Uposhakha Naogaon", "Code": 853},
    {"Sl": 339, "BranchName": "Hilli Bandar Uposhakha Dinajpur", "Code": 854},
    {"Sl": 340, "BranchName": "Khetalal Uposhakha Joypurhat", "Code": 855},
    {"Sl": 341, "BranchName": "Raikali Bazar Uposhakha Joypurhat", "Code": 856},
    {"Sl": 342, "BranchName": "Ghoraghat Uposhakha  Dinajpur", "Code": 857},
    {"Sl": 343, "BranchName": "Nawhata Bazar Uposhakha Rajshahi", "Code": 860},
    {"Sl": 344, "BranchName": "Rajshahi Uposhahar Rajshahi", "Code": 861},
    {"Sl": 345, "BranchName": "Rajshahi Laxmipur Uposhakha", "Code": 862},
    {"Sl": 346, "BranchName": "Rajshahi Court Bazar Uposhakha", "Code": 863},
    {"Sl": 347, "BranchName": "Sherpur Road Colony Uposhakha", "Code": 870},
    {
      "Sl": 348,
      "BranchName": "Sherpur Upozilla Uposhakha  Bogura",
      "Code": 871
    },
    {"Sl": 349, "BranchName": "Dhupchachia Uposhakha  Bogura", "Code": 872},
    {"Sl": 350, "BranchName": "Gabtoli Upozila Uposhakha Bogura", "Code": 873},
    {"Sl": 351, "BranchName": "Chelopara Uposhakha Bogura", "Code": 874},
    {"Sl": 352, "BranchName": "Bogura Bou Bazar Uposhakha Bogura", "Code": 875},
    {"Sl": 353, "BranchName": "Bogura Shibganj Uposhakha Bogura", "Code": 876},
    {"Sl": 354, "BranchName": "Bogura Uposhahar Uposhakha Bogura", "Code": 877},
    {"Sl": 355, "BranchName": "Godarpara Uposhakha", "Code": 878},
    {"Sl": 356, "BranchName": "Biman More Uposhakha Bogura", "Code": 879},
    {"Sl": 357, "BranchName": "Ishwardi Uposhakha Pabna", "Code": 880},
    {"Sl": 358, "BranchName": "Tebunia Uposhakha Pabna", "Code": 881},
    {"Sl": 359, "BranchName": "Dapunia Bazar Uposhakha Pabna", "Code": 882},
    {"Sl": 360, "BranchName": "Ekdanta Bazar Uposhakha Pabna", "Code": 883},
    {"Sl": 361, "BranchName": "Chatmohor Uposhakha Pabna", "Code": 884},
    {"Sl": 362, "BranchName": "Sujanagar Uposhakha Pabna", "Code": 885},
    {"Sl": 363, "BranchName": "Lalpur Natore Uposhakha Natore", "Code": 886},
    {"Sl": 364, "BranchName": "Baraigram Natore", "Code": 887},
    {"Sl": 365, "BranchName": "Ataikula Uposhakha Pabna", "Code": 888},
    {"Sl": 366, "BranchName": "Bonpara Natore", "Code": 889},
    {"Sl": 367, "BranchName": "Shantahar Uposhakha Bogura", "Code": 890},
    {"Sl": 368, "BranchName": "Chowmashia Uposhakha Naogaon", "Code": 891},
    {"Sl": 369, "BranchName": "Niamatpur Uposhakha Naogaon", "Code": 892},
    {"Sl": 370, "BranchName": "Raninagar Uposhakha Naogaon", "Code": 893},
    {"Sl": 371, "BranchName": "Abadpukur Uposhakha Naogaon", "Code": 894},
    {"Sl": 372, "BranchName": "Sapahar Uposhakha Naogaon", "Code": 895},
    {"Sl": 373, "BranchName": "Mohadevpur Uposhakha Naogaon", "Code": 896},
    {"Sl": 374, "BranchName": "Badalgachi Uposhakha Naogaon", "Code": 897},
    {"Sl": 375, "BranchName": "Nazipur Uposhakha Naogaon", "Code": 898},
    {"Sl": 376, "BranchName": "Shibganj Upo. Chapai Nawabganj", "Code": 900},
    {"Sl": 377, "BranchName": "Godagari Rajshahi", "Code": 901},
    {
      "Sl": 378,
      "BranchName": "Rohanpur Uposhakha Chapainawabganj",
      "Code": 902
    },
    {"Sl": 379, "BranchName": "Kansat Chapai Nawabganj", "Code": 903},
    {"Sl": 380, "BranchName": "Kakonhat Uposhakha Rajshahi", "Code": 904},
    {
      "Sl": 381,
      "BranchName": "Nachole Bazar Upo Chapai Nawabganj",
      "Code": 905
    },
    {"Sl": 382, "BranchName": "Charghat Uposhakha", "Code": 910},
    {"Sl": 383, "BranchName": "Durgapur Bazar Uposhakha Rajshahi", "Code": 911},
    {"Sl": 384, "BranchName": "Bagha Uposhakha Rajshahi", "Code": 912},
    {"Sl": 385, "BranchName": "Arani Uposhakha Rajshahi", "Code": 913},
    {"Sl": 386, "BranchName": "Qadirabad Cantonment Natore", "Code": 914},
    {"Sl": 387, "BranchName": "Tamai Uposhakha Sirajganj", "Code": 920},
    {
      "Sl": 388,
      "BranchName": "Paikosha Bazar Uposhakha Sirajganj",
      "Code": 921
    },
    {
      "Sl": 389,
      "BranchName": "Satbaria Bazar Uposhakha Sirajganj",
      "Code": 922
    },
    {
      "Sl": 390,
      "BranchName": "Sirajganj Sadar Uposhakha Sirajganj",
      "Code": 923
    },
    {"Sl": 391, "BranchName": "Jamtoil Bazar Uposhakha Sirajganj", "Code": 924},
    {"Sl": 392, "BranchName": "Shahajadpur Sirajganj Uposhakha", "Code": 925},
    {"Sl": 393, "BranchName": "Enayetpur Sirajganj Uposhakha", "Code": 926},
    {"Sl": 394, "BranchName": "Ullapara Uposhakha Sirajganj", "Code": 927},
    {"Sl": 395, "BranchName": "Harina Pipulbaria Sirajganj", "Code": 928},
    {"Sl": 396, "BranchName": "Salanga Sirajganj", "Code": 929},
    {"Sl": 397, "BranchName": "Santhia Uposhakha Pabna", "Code": 930},
    {"Sl": 398, "BranchName": "Nagarbari Uposhakha Pabna", "Code": 931},
    {"Sl": 399, "BranchName": "Nakalia Bazar Uposhakha Pabna", "Code": 932},
    {"Sl": 400, "BranchName": "Bera Uposhakha Pabna", "Code": 933},
    {"Sl": 401, "BranchName": "Bonogram Bazar Uposhakha  Pabna", "Code": 934},
    {"Sl": 402, "BranchName": "Bhawaniganj Uposhakha", "Code": 940},
    {"Sl": 403, "BranchName": "Natore Sadar Uposhakha Natore", "Code": 941},
    {"Sl": 404, "BranchName": "Mohonganj Uposhakha Rajshahi", "Code": 942},
    {"Sl": 405, "BranchName": "Naldanga Uposhakha Natore", "Code": 943},
    {"Sl": 406, "BranchName": "Gurudashpur Uposhakha Natore", "Code": 944},
    {"Sl": 407, "BranchName": "Keshorhat Uposhakha Rajshahi", "Code": 945},
    {"Sl": 408, "BranchName": "Hatgangopara Uposhakha Rajshahi", "Code": 946},
    {"Sl": 409, "BranchName": "Singra Uposhakha Natore", "Code": 947},
    {"Sl": 410, "BranchName": "Mokamtola Uposhakha Bogura", "Code": 951},
    {"Sl": 411, "BranchName": "Borogola Uposhakha Bogura", "Code": 952},
    {"Sl": 412, "BranchName": "Namuja Hat Uposhakha Bogura", "Code": 953},
    {"Sl": 413, "BranchName": "Majhira Uposhakha Bogura", "Code": 954},
    {"Sl": 414, "BranchName": "Kichak Uposhakha Bogura", "Code": 955},
    {"Sl": 415, "BranchName": "Dhunat Uposhakha Bogura", "Code": 956},
    {"Sl": 416, "BranchName": "Chandaikona Uposhakha Sirajganj", "Code": 957},
    {"Sl": 417, "BranchName": "Nandigram Bus Stand Bogura", "Code": 958},
    {"Sl": 418, "BranchName": "Kahaloo Uposhakha Bogura", "Code": 959},
    {"Sl": 419, "BranchName": "Noymile  Bogura Uposhakha Bogura", "Code": 960},
    {"Sl": 420, "BranchName": "Nimgachi Uposhakha Sirajganj", "Code": 971},
    {
      "Sl": 421,
      "BranchName": "Dhangora Bazar Uposhakha Sirajganj",
      "Code": 972
    },
    {"Sl": 422, "BranchName": "Sonatola Uposhakha  Bogura", "Code": 996},
    {"Sl": 423, "BranchName": "Sariakandi Uposhakha  Bogura", "Code": 997},
    {"Sl": 424, "BranchName": "Mohasthan Garh Uposhakha  Bogura", "Code": 998},
    {"Sl": 425, "BranchName": "Principal Branch", "Code": 1001},
    {"Sl": 426, "BranchName": "Gulshan Branch", "Code": 1002},
    {"Sl": 427, "BranchName": "Narayanganj Branch", "Code": 1003},
    {"Sl": 428, "BranchName": "Moulvi Bazar Branch  Dhaka", "Code": 1004},
    {"Sl": 429, "BranchName": "Islampur Branch", "Code": 1005},
    {"Sl": 430, "BranchName": "Dhanmondi Branch", "Code": 1006},
    {"Sl": 431, "BranchName": "Shantinagar Branch", "Code": 1007},
    {"Sl": 432, "BranchName": "Federation Branch", "Code": 1008},
    {"Sl": 433, "BranchName": "Bangshal Branch", "Code": 1011},
    {"Sl": 434, "BranchName": "Mirpur Branch", "Code": 1013},
    {"Sl": 435, "BranchName": "Elephant Road Branch", "Code": 1014},
    {"Sl": 436, "BranchName": "Netaiganj Branch", "Code": 1016},
    {"Sl": 437, "BranchName": "Kawran Bazar Branch", "Code": 1017},
    {"Sl": 438, "BranchName": "Malibagh Branch", "Code": 1019},
    {"Sl": 439, "BranchName": "Naya Paltan Branch", "Code": 1020},
    {"Sl": 440, "BranchName": "Mymensingh Branch", "Code": 1022},
    {"Sl": 441, "BranchName": "Faridpur Branch", "Code": 1023},
    {"Sl": 442, "BranchName": "Uttara Branch", "Code": 1024},
    {"Sl": 443, "BranchName": "Lalmatia Branch", "Code": 1025},
    {"Sl": 444, "BranchName": "Pallabi Branch", "Code": 1027},
    {"Sl": 445, "BranchName": "North Brooke Hall Road Branch", "Code": 1028},
    {"Sl": 446, "BranchName": "Nawabpur Road Branch", "Code": 1029},
    {"Sl": 447, "BranchName": "Bashundhara Branch", "Code": 1070},
    {"Sl": 448, "BranchName": "Pragati Sarani Branch", "Code": 1072},
    {"Sl": 449, "BranchName": "Tangail Branch", "Code": 1076},
    {"Sl": 450, "BranchName": "Stock Exchange Branch", "Code": 1090},
    {"Sl": 451, "BranchName": "Tanbazar Branch", "Code": 1091},
    {"Sl": 452, "BranchName": "Shariatpur Branch", "Code": 1092},
    {"Sl": 453, "BranchName": "Mohakhali Branch", "Code": 1094},
    {"Sl": 454, "BranchName": "Banani Branch", "Code": 1096},
    {"Sl": 455, "BranchName": "Ghorasal Branch", "Code": 1109},
    {"Sl": 456, "BranchName": "Narsingdi Branch", "Code": 1110},
    {"Sl": 457, "BranchName": "Bajitpur Branch", "Code": 1112},
    {"Sl": 458, "BranchName": "Muktarpur Branch", "Code": 1115},
    {"Sl": 459, "BranchName": "Madhabdi Branch", "Code": 1118},
    {"Sl": 460, "BranchName": "Konabari Branch", "Code": 1121},
    {"Sl": 461, "BranchName": "Takerhat Branch", "Code": 1126},
    {"Sl": 462, "BranchName": "Savar Bazar Branch", "Code": 1171},
    {"Sl": 463, "BranchName": "Panchaboti Branch", "Code": 1173},
    {"Sl": 464, "BranchName": "Tongi SME Krishi Branch", "Code": 1174},
    {"Sl": 465, "BranchName": "Nawabganj SME Krishi Branch", "Code": 1175},
    {"Sl": 466, "BranchName": "Board Bazar Branch", "Code": 1177},
    {"Sl": 467, "BranchName": "Dhamrai SME Krishi Branch", "Code": 1178},
    {"Sl": 468, "BranchName": "Dania Branch", "Code": 1193},
    {"Sl": 469, "BranchName": "Keraniganj Branch", "Code": 1195},
    {"Sl": 470, "BranchName": "Ashulia Branch", "Code": 1197},
    {"Sl": 471, "BranchName": "Rupgonj Branch", "Code": 1198},
    {"Sl": 472, "BranchName": "Mohammadpur Branch", "Code": 1201},
    {"Sl": 473, "BranchName": "Gulshan Tejgaon Link Road Branch", "Code": 1203},
    {"Sl": 474, "BranchName": "Chandra SME Krishi Branch", "Code": 1205},
    {"Sl": 475, "BranchName": "Manikgonj Branch", "Code": 1206},
    {"Sl": 476, "BranchName": "Gabtoli Bagbari Branch", "Code": 1207},
    {"Sl": 477, "BranchName": "Konapara Branch", "Code": 1208},
    {"Sl": 478, "BranchName": "Shahjalal Avenue Branch  Dhaka", "Code": 1211},
    {"Sl": 479, "BranchName": "Meghola Bazar Branch", "Code": 1213},
    {"Sl": 480, "BranchName": "Garibe Newaz Avenue Branch", "Code": 1217},
    {"Sl": 481, "BranchName": "Hasnabad Branch", "Code": 1218},
    {"Sl": 482, "BranchName": "Aganagar Branch", "Code": 1219},
    {"Sl": 483, "BranchName": "Seed Store Bazar Branch", "Code": 1221},
    {"Sl": 484, "BranchName": "Shibu Market Branch", "Code": 1224},
    {"Sl": 485, "BranchName": "Gazipur Chowrasta Branch", "Code": 1225},
    {"Sl": 486, "BranchName": "Mawna Branch Gazipur", "Code": 1226},
    {"Sl": 487, "BranchName": "Sherpur Branch  Sherpur", "Code": 1227},
    {"Sl": 488, "BranchName": "Bandar Branch  Narayanganj", "Code": 1228},
    {"Sl": 489, "BranchName": "Jamalpur Branch  Jamalpur", "Code": 1229},
    {"Sl": 490, "BranchName": "Isapura Bazar Branch", "Code": 1230},
    {"Sl": 491, "BranchName": "Karatia Branch", "Code": 1231},
    {"Sl": 492, "BranchName": "Darus Salam Road Branch  Dhaka", "Code": 1232},
    {"Sl": 493, "BranchName": "Panchdona Branch", "Code": 1233},
    {"Sl": 494, "BranchName": "Arshinagar Branch  Dhaka.", "Code": 1234},
    {"Sl": 495, "BranchName": "Bhuigar Branch  Narayanganj", "Code": 1235},
    {"Sl": 496, "BranchName": "Cherag Ali Branch  Gazipur", "Code": 1237},
    {"Sl": 497, "BranchName": "Federation Branch", "Code": 1238},
    {"Sl": 498, "BranchName": "Bhawal Mirzapur Branch  Gazipur", "Code": 1239},
    {"Sl": 499, "BranchName": "Kapasia Branch  Gazipur", "Code": 1240},
    {"Sl": 500, "BranchName": "Shafipur Branch  Gazipur.", "Code": 1244},
    {"Sl": 501, "BranchName": "Banasree Branch  Dhaka.", "Code": 1245},
    {"Sl": 502, "BranchName": "Goalanda Branch", "Code": 1248},
    {"Sl": 503, "BranchName": "Khilgaon Branch", "Code": 1249},
    {"Sl": 504, "BranchName": "Zirani Bazar Branch  Dhaka", "Code": 1250},
    {"Sl": 505, "BranchName": "Kishoreganj Branch  Kishoreganj", "Code": 1251},
    {"Sl": 506, "BranchName": "Nikunja Branch  Dhaka", "Code": 1252},
    {"Sl": 507, "BranchName": "Araihazar Branch  Narayanganj", "Code": 1253},
    {"Sl": 508, "BranchName": "Sonargaon Branch  Narayanganj", "Code": 1254},
    {"Sl": 509, "BranchName": "Dhanbari Branch  Tangail.", "Code": 1255},
    {"Sl": 510, "BranchName": "Kashiani Branch", "Code": 1256},
    {"Sl": 511, "BranchName": "Netrokona Branch", "Code": 1257},
    {"Sl": 512, "BranchName": "Bakshiganj Branch   Jamalpur", "Code": 1258},
    {"Sl": 513, "BranchName": "Panchar Branch  Madaripur", "Code": 1259},
    {"Sl": 514, "BranchName": "Madaripur Branch", "Code": 1270},
    {"Sl": 515, "BranchName": "Gopalganj Branch", "Code": 1273},
    {"Sl": 516, "BranchName": "Agrabad Branch", "Code": 2030},
    {"Sl": 517, "BranchName": "Khatunganj Branch", "Code": 2031},
    {"Sl": 518, "BranchName": "Brahmanbaria Branch", "Code": 2034},
    {"Sl": 519, "BranchName": "Comilla Branch", "Code": 2035},
    {"Sl": 520, "BranchName": "Patiya Branch  Chattogram", "Code": 2036},
    {"Sl": 521, "BranchName": "Chawk Bazar Branch", "Code": 2040},
    {"Sl": 522, "BranchName": "Feni Branch", "Code": 2041},
    {"Sl": 523, "BranchName": "Shah Amanat Market Branch", "Code": 2042},
    {"Sl": 524, "BranchName": "Coxs Bazar Branch", "Code": 2044},
    {"Sl": 525, "BranchName": "Sheikh Mujib Road Branch", "Code": 2045},
    {"Sl": 526, "BranchName": "Choumuhani Branch", "Code": 2050},
    {"Sl": 527, "BranchName": "CDA Avenue Branch", "Code": 2054},
    {"Sl": 528, "BranchName": "Alankar More Branch", "Code": 2056},
    {"Sl": 529, "BranchName": "Noju Miah Hat Branch", "Code": 2132},
    {"Sl": 530, "BranchName": "Hathazari Branch", "Code": 2137},
    {"Sl": 531, "BranchName": "Companyganj Branch", "Code": 2148},
    {"Sl": 532, "BranchName": "Fatikchari Branch", "Code": 2152},
    {"Sl": 533, "BranchName": "Madam Bibir Hat Branch", "Code": 2153},
    {"Sl": 534, "BranchName": "Ashuganj Branch", "Code": 2155},
    {"Sl": 535, "BranchName": "Chandina Branch", "Code": 2157},
    {"Sl": 536, "BranchName": "Rangamati Branch", "Code": 2204},
    {"Sl": 537, "BranchName": "Gouripur Bazar Branch", "Code": 2210},
    {"Sl": 538, "BranchName": "Miah Bazar Branch", "Code": 2214},
    {"Sl": 539, "BranchName": "Bandartila Branch", "Code": 2220},
    {"Sl": 540, "BranchName": "Chandraganj Branch", "Code": 2222},
    {"Sl": 541, "BranchName": "Anwara Branch  Chittagong.", "Code": 2236},
    {"Sl": 542, "BranchName": "Khulshi Branch  Chittagong", "Code": 2241},
    {"Sl": 543, "BranchName": "Kachua Branch  Chandpur", "Code": 2246},
    {"Sl": 544, "BranchName": "Moynamoti Branch  Comilla", "Code": 2247},
    {"Sl": 545, "BranchName": "Akhaura Branch", "Code": 2250},
    {"Sl": 546, "BranchName": "Keranihat Branch  Satkania  CTG.", "Code": 2251},
    {"Sl": 547, "BranchName": "Chakaria Branch  Coxs Bazar", "Code": 2252},
    {"Sl": 548, "BranchName": "Laxmipur Branch", "Code": 2253},
    {"Sl": 549, "BranchName": "Laksham Branch", "Code": 2254},
    {"Sl": 550, "BranchName": "Sandwip Branch", "Code": 2255},
    {"Sl": 551, "BranchName": "Boalkhali Branch", "Code": 2256},
    {"Sl": 552, "BranchName": "Khagrachari Branch", "Code": 2267},
    {"Sl": 553, "BranchName": "Bandarban Branch", "Code": 2268},
    {"Sl": 554, "BranchName": "Sylhet Branch", "Code": 3033},
    {"Sl": 555, "BranchName": "Subid Bazar Branch", "Code": 3043},
    {"Sl": 556, "BranchName": "Moulvibazar District Branch", "Code": 3046},
    {"Sl": 557, "BranchName": "Shreemongal Branch", "Code": 3047},
    {"Sl": 558, "BranchName": "Uposhohar Branch", "Code": 3049},
    {"Sl": 559, "BranchName": "Beani Bazar Branch", "Code": 3138},
    {"Sl": 560, "BranchName": "Ambarkhana Branch", "Code": 3139},
    {"Sl": 561, "BranchName": "Goala Bazar Branch", "Code": 3151},
    {"Sl": 562, "BranchName": "Habiganj Branch", "Code": 3216},
    {"Sl": 563, "BranchName": "Madhabpur Branch  Habiganj.", "Code": 3242},
    {"Sl": 564, "BranchName": "Juri Branch", "Code": 3251},
    {"Sl": 565, "BranchName": "Sunamganj Branch", "Code": 3252},
    {"Sl": 566, "BranchName": "Khulna Branch", "Code": 4060},
    {"Sl": 567, "BranchName": "Jessore Branch", "Code": 4061},
    {"Sl": 568, "BranchName": "Kushtia Branch", "Code": 4062},
    {"Sl": 569, "BranchName": "Satkhira Branch", "Code": 4065},
    {"Sl": 570, "BranchName": "Boro Bazar Branch", "Code": 4067},
    {"Sl": 571, "BranchName": "Noapara Branch", "Code": 4163},
    {"Sl": 572, "BranchName": "Benapole Branch", "Code": 4166},
    {"Sl": 573, "BranchName": "Kaliganj SME Krishi Branch", "Code": 4168},
    {"Sl": 574, "BranchName": "Poradah Branch", "Code": 4169},
    {"Sl": 575, "BranchName": "Bagerhat Branch", "Code": 4212},
    {"Sl": 576, "BranchName": "Sonadanga Branch", "Code": 4223},
    {"Sl": 577, "BranchName": "Darshana Branch", "Code": 4224},
    {"Sl": 578, "BranchName": "Narail Branch", "Code": 4260},
    {"Sl": 579, "BranchName": "Magura Branch", "Code": 4261},
    {"Sl": 580, "BranchName": "Barisal Branch", "Code": 5064},
    {"Sl": 581, "BranchName": "Bhola Branch", "Code": 5202},
    {"Sl": 582, "BranchName": "Jhalokathi Branch  Jhalokathi", "Code": 5243},
    {"Sl": 583, "BranchName": "Patuakhali Branch  Patuakhali", "Code": 5244},
    {"Sl": 584, "BranchName": "Bhandaria BRANCH", "Code": 5245},
    {"Sl": 585, "BranchName": "Pirojpur Branch", "Code": 5262},
    {"Sl": 586, "BranchName": "Barguna Branch", "Code": 5266},
    {"Sl": 587, "BranchName": "Joypurhat Branch", "Code": 6058},
    {"Sl": 588, "BranchName": "Rajshahi Branch", "Code": 6080},
    {"Sl": 589, "BranchName": "Rangpur Branch", "Code": 6081},
    {"Sl": 590, "BranchName": "Bogra Branch", "Code": 6082},
    {"Sl": 591, "BranchName": "Dinajpur Branch", "Code": 6083},
    {"Sl": 592, "BranchName": "Pabna Branch", "Code": 6084},
    {"Sl": 593, "BranchName": "Naogaon Branch", "Code": 6085},
    {"Sl": 594, "BranchName": "Chapai Nawabganj Branch", "Code": 6086},
    {"Sl": 595, "BranchName": "Setabgonj SME Krishi Branch", "Code": 6179},
    {"Sl": 596, "BranchName": "Baneshwar Branch", "Code": 6187},
    {"Sl": 597, "BranchName": "Belkuchi Branch", "Code": 6188},
    {"Sl": 598, "BranchName": "Kashinathpur SME Krishi Branch", "Code": 6189},
    {"Sl": 599, "BranchName": "Birol Bazar Branch", "Code": 6209},
    {"Sl": 600, "BranchName": "Taherpur Branch", "Code": 6215},
    {"Sl": 601, "BranchName": "Sirajganj Branch", "Code": 6216},
    {"Sl": 602, "BranchName": "Palashbari Branch  Gaibandha", "Code": 6217},
    {"Sl": 603, "BranchName": "Panchagarh Branch", "Code": 6263},
    {"Sl": 604, "BranchName": "Natore Branch", "Code": 6264},
    {"Sl": 605, "BranchName": "Gaibandha Branch", "Code": 6271},
    {"Sl": 606, "BranchName": "Nilphamari Branch", "Code": 6275},
    {"Sl": 607, "BranchName": "Nazimuddin Road Uposhakha  Dhaka", "Code": 7020},
    {"Sl": 608, "BranchName": "Becharam Dewri Uposhakha  Dhaka", "Code": 7021},
    {"Sl": 609, "BranchName": "Lalbagh Uposhakha Dhaka", "Code": 7022},
    {"Sl": 610, "BranchName": "Showari Ghat Uposhakha Dhaka", "Code": 7023},
    {"Sl": 611, "BranchName": "Choto Katra Uposhakha Dhaka", "Code": 7024},
    {"Sl": 612, "BranchName": "Islambagh Uposhakha Dhaka", "Code": 7025},
    {"Sl": 613, "BranchName": "Kamrangir Char Uposhakha", "Code": 7030},
    {"Sl": 614, "BranchName": "Badamtoli Uposhakha", "Code": 7031},
    {"Sl": 615, "BranchName": "Rony Market Uposhakha  Dhaka", "Code": 7032},
    {"Sl": 616, "BranchName": "Midford Road Uposhakha  Dhaka", "Code": 7033},
    {"Sl": 617, "BranchName": "Armanitola Uposhakha Dhaka", "Code": 7034},
    {"Sl": 618, "BranchName": "Zindabahar First Lane Dhaka", "Code": 7035},
    {"Sl": 619, "BranchName": "Wais Ghat Uposhakha Dhaka", "Code": 7036},
    {"Sl": 620, "BranchName": "Zigatola Uposhakha", "Code": 7045},
    {"Sl": 621, "BranchName": "Green Road Uposhakha Dhaka", "Code": 7046},
    {"Sl": 622, "BranchName": "Tannery More Uposhakha Dhaka", "Code": 7047},
    {"Sl": 623, "BranchName": "Rayer Bazar Uposhakha Dhaka", "Code": 7048},
    {"Sl": 624, "BranchName": "Mouchak Uposhakha", "Code": 7065},
    {"Sl": 625, "BranchName": "Moghbazar Uposhakha", "Code": 7066},
    {"Sl": 626, "BranchName": "Malibagh Moor Uposhakha Dhaka", "Code": 7067},
    {"Sl": 627, "BranchName": "Malibagh Kancha Bazar Uposhakha", "Code": 7068},
    {
      "Sl": 628,
      "BranchName": "Abul Hasnat Road Uposhakha  Dhaka",
      "Code": 7095
    },
    {
      "Sl": 629,
      "BranchName": "Kazi Alauddin Road Uposhakha Dhaka",
      "Code": 7096
    },
    {"Sl": 630, "BranchName": "Naya Bazar Moor Uposhakha Dhaka", "Code": 7097},
    {
      "Sl": 631,
      "BranchName": "MirpurSherEBangla Stadium Uposhakha",
      "Code": 7110
    },
    {"Sl": 632, "BranchName": "Kachukhet Uposhakha", "Code": 7111},
    {"Sl": 633, "BranchName": "Borobagh Uposhakha  Dhaka", "Code": 7112},
    {"Sl": 634, "BranchName": "Senpara Parbata Uposhakha  Dhaka", "Code": 7113},
    {
      "Sl": 635,
      "BranchName": "Taltola Bazar Road Uposhakha  Dhaka",
      "Code": 7114
    },
    {"Sl": 636, "BranchName": "East Kafrul Uposhakha Dhaka", "Code": 7115},
    {"Sl": 637, "BranchName": "Shewrapara Uposhakha Dhaka", "Code": 7116},
    {"Sl": 638, "BranchName": "Hatirpool Uposhakha", "Code": 7135},
    {"Sl": 639, "BranchName": "Azimpur Uposhakha  Dhaka", "Code": 7136},
    {"Sl": 640, "BranchName": "Science Lab Uposhakha Dhaka", "Code": 7137},
    {"Sl": 641, "BranchName": "Chapra Mosjid Azimpur Dhaka", "Code": 7138},
    {"Sl": 642, "BranchName": "Dilu Road Uposhakha", "Code": 7155},
    {"Sl": 643, "BranchName": "Panthapath Uposhakha", "Code": 7156},
    {"Sl": 644, "BranchName": "Banglamotor Uposhakha  Dhaka", "Code": 7157},
    {
      "Sl": 645,
      "BranchName": "Tejturi Bazar RoadUposhakha Dhaka",
      "Code": 7158
    },
    {"Sl": 646, "BranchName": "Indira Road Uposhakha Dhaka", "Code": 7159},
    {"Sl": 647, "BranchName": "Tejkunipara Uposhakha Dhaka", "Code": 7160},
    {"Sl": 648, "BranchName": "Holiday Inn Dhaka City Center", "Code": 7161},
    {"Sl": 649, "BranchName": "WAPDA Road Uposhakha", "Code": 7180},
    {"Sl": 650, "BranchName": "Noyatola Road Uposhakha  Dhaka", "Code": 7181},
    {"Sl": 651, "BranchName": "TV Center Uposhakha  Dhaka", "Code": 7182},
    {
      "Sl": 652,
      "BranchName": "Rampura Bou Bazar Uposhakha Dhaka",
      "Code": 7183
    },
    {"Sl": 653, "BranchName": "Bijoynagar Uposhakha", "Code": 7200},
    {"Sl": 654, "BranchName": "Paltan Uposhakha", "Code": 7201},
    {"Sl": 655, "BranchName": "VIP Road Uposhakha  Dhaka", "Code": 7202},
    {"Sl": 656, "BranchName": "Segunbagicha Uposhakha Dhaka", "Code": 7203},
    {
      "Sl": 657,
      "BranchName": "Bangabandhu Avenue Uposhakha Dhaka",
      "Code": 7204
    },
    {"Sl": 658, "BranchName": "Kamlapur Bazar Uposhakha Dhaka", "Code": 7205},
    {"Sl": 659, "BranchName": "Arambagh Uposhakha  Dhaka", "Code": 7206},
    {"Sl": 660, "BranchName": "Gausul Azam Avenue Uposhakha", "Code": 7220},
    {"Sl": 661, "BranchName": "Uttara Sector 6 Uposhakha  Dhaka", "Code": 7221},
    {"Sl": 662, "BranchName": "Uttarkhan Mazar Road  Uposhakha", "Code": 7222},
    {"Sl": 663, "BranchName": "Moinertek Uposhakha  Dhaka", "Code": 7223},
    {"Sl": 664, "BranchName": "Ashkona Bazar Uposhakha Dhaka", "Code": 7224},
    {"Sl": 665, "BranchName": "Kanchkura Uposhakha Dhaka", "Code": 7225},
    {"Sl": 666, "BranchName": "Nikunja 2 Uposhakha Dhaka", "Code": 7226},
    {"Sl": 667, "BranchName": "Pakuria Bazar Uposhakha Dhaka", "Code": 7227},
    {
      "Sl": 668,
      "BranchName": "Dakshinkhan Bazar Uposhakha Dhaka",
      "Code": 7228
    },
    {
      "Sl": 669,
      "BranchName": "Joynal Market  Dakshinkhan  Dhaka",
      "Code": 7229
    },
    {
      "Sl": 670,
      "BranchName": "Jahura Market Road Uposhakha Dhaka",
      "Code": 7230
    },
    {"Sl": 671, "BranchName": "Azampur Kancha Bazar Upo. Dhaka", "Code": 7231},
    {"Sl": 672, "BranchName": "Baunia Bazar Uposhakha Dhaka", "Code": 7232},
    {"Sl": 673, "BranchName": "Asad Gate Uposhakha", "Code": 7245},
    {"Sl": 674, "BranchName": "Monipuripara Uposhakha  Dhaka", "Code": 7246},
    {"Sl": 675, "BranchName": "Shankar Uposhakha  Dhaka", "Code": 7247},
    {"Sl": 676, "BranchName": "Town Hall Uposhakha Dhaka", "Code": 7248},
    {"Sl": 677, "BranchName": "Sat Masjid Road Uposhakha Dhaka", "Code": 7249},
    {"Sl": 678, "BranchName": "Mirpur DOHS Uposhakha", "Code": 7265},
    {
      "Sl": 679,
      "BranchName": "Pallabi Phase   II Uposhakha  Dhaka",
      "Code": 7266
    },
    {
      "Sl": 680,
      "BranchName": "Pallabi Extension Uposhakha  Dhaka",
      "Code": 7267
    },
    {"Sl": 681, "BranchName": "Banarasi Palli Uposhakha  Dhaka", "Code": 7268},
    {"Sl": 682, "BranchName": "Rupnagar Uposhakha  Dhaka", "Code": 7269},
    {"Sl": 683, "BranchName": "Lalmati Uposhakha Dhaka", "Code": 7270},
    {"Sl": 684, "BranchName": "Mirpur 6 Uposhakha Dhaka", "Code": 7271},
    {"Sl": 685, "BranchName": "Mirpur 12 Uposhakha Dhaka", "Code": 7272},
    {"Sl": 686, "BranchName": "Dewanpara Uposhakha Dhaka", "Code": 7273},
    {"Sl": 687, "BranchName": "ECB Chattar Uposhakha Dhaka", "Code": 7274},
    {"Sl": 688, "BranchName": "Shyampur Uposhakha Dhaka", "Code": 7285},
    {"Sl": 689, "BranchName": "Roy Saheb Bazar Moor Uposhakha", "Code": 7286},
    {"Sl": 690, "BranchName": "Lalkuthi Uposhakha Dhaka", "Code": 7287},
    {"Sl": 691, "BranchName": "Sutrapur Uposhakha Dhaka", "Code": 7288},
    {"Sl": 692, "BranchName": "Laxmibazar Uposhakha Dhaka", "Code": 7289},
    {"Sl": 693, "BranchName": "Gendaria Uposhakha  Dhaka", "Code": 7300},
    {"Sl": 694, "BranchName": "Distillery Road Uposhakha  Dhaka", "Code": 7301},
    {"Sl": 695, "BranchName": "Dholaikhal Uposhakha Dhaka", "Code": 7302},
    {"Sl": 696, "BranchName": "BCC Road Uposhakha Dhaka", "Code": 7303},
    {"Sl": 697, "BranchName": "Kuril Chowrasta Uposhakha", "Code": 7315},
    {"Sl": 698, "BranchName": "Bhatara Uposhakha", "Code": 7316},
    {
      "Sl": 699,
      "BranchName": "Joar Shahara Bazar Uposhakha  Dhaka",
      "Code": 7317
    },
    {"Sl": 700, "BranchName": "Madani Avenue Uposhakha Dhaka", "Code": 7318},
    {"Sl": 701, "BranchName": "Nadda Uposhakha Dhaka", "Code": 7319},
    {"Sl": 702, "BranchName": "Beraid Uposhakha Dhaka", "Code": 7320},
    {"Sl": 703, "BranchName": "Kuratoli Bazar Uposhakha Dhaka", "Code": 7321},
    {
      "Sl": 704,
      "BranchName": "Khandaker Bari Moor Uposhakha Dhaka",
      "Code": 7323
    },
    {"Sl": 705, "BranchName": "Satarkul Uposhakha", "Code": 7335},
    {
      "Sl": 706,
      "BranchName": "Middle Badda Post Office Road Dhaka",
      "Code": 7336
    },
    {"Sl": 707, "BranchName": "Merul Badda Uposhakha Dhaka", "Code": 7337},
    {"Sl": 708, "BranchName": "Gulshan Badda Link Road Dhaka", "Code": 7338},
    {"Sl": 709, "BranchName": "Shahjadpur Uposhakha Dhaka", "Code": 7339},
    {
      "Sl": 710,
      "BranchName": "Gulshan Lake Drive Road Upo. Dhaka",
      "Code": 7340
    },
    {"Sl": 711, "BranchName": "Ittefaq More Uposhakha", "Code": 7355},
    {"Sl": 712, "BranchName": "Sayadabad Uposhakha  Dhaka", "Code": 7356},
    {"Sl": 713, "BranchName": "Golapbagh Uposhakha  Dhaka", "Code": 7357},
    {
      "Sl": 714,
      "BranchName": "R.K. Mission Road Uposhakha Dhaka",
      "Code": 7358
    },
    {"Sl": 715, "BranchName": "Hatkhola Fokir Banu Market Dhaka", "Code": 7359},
    {"Sl": 716, "BranchName": "Rasulbagh Uposhakha Dhaka", "Code": 7375},
    {"Sl": 717, "BranchName": "Niketon Bazar Uposhakha Dhaka", "Code": 7376},
    {"Sl": 718, "BranchName": "Banani Bazar Uposhakha  Dhaka", "Code": 7395},
    {"Sl": 719, "BranchName": "Banani Chairmanbari Upo. Dhaka", "Code": 7396},
    {"Sl": 720, "BranchName": "Banani Graveyard Road Dhaka", "Code": 7397},
    {"Sl": 721, "BranchName": "Tushardhara Uposhakha", "Code": 7415},
    {"Sl": 722, "BranchName": "Rayerbagh Uposhakha", "Code": 7416},
    {"Sl": 723, "BranchName": "Matuail Uposhakha", "Code": 7417},
    {"Sl": 724, "BranchName": "Nurpur Uposhakha Dhaka", "Code": 7418},
    {"Sl": 725, "BranchName": "Swamibagh Uposhakha Dhaka", "Code": 7419},
    {"Sl": 726, "BranchName": "Dholaipar Uposhakha Dhaka", "Code": 7420},
    {"Sl": 727, "BranchName": "Polashpur Uposhakha Dhaka", "Code": 7421},
    {"Sl": 728, "BranchName": "East Jurain Uposhakha Dhaka", "Code": 7422},
    {"Sl": 729, "BranchName": "Shuti Khalpar Uposhakha Dhaka", "Code": 7423},
    {"Sl": 730, "BranchName": "Mohammadbag Uposhakha Dhaka", "Code": 7424},
    {"Sl": 731, "BranchName": "Dhaka Uddan Uposhakha", "Code": 7435},
    {"Sl": 732, "BranchName": "Mohammadpur Bus Stand Uposhakha", "Code": 7436},
    {"Sl": 733, "BranchName": "Babor Road Uposhakha  Dhaka", "Code": 7437},
    {
      "Sl": 734,
      "BranchName": "Mohammadia Housing Main Road Dhaka",
      "Code": 7438
    },
    {"Sl": 735, "BranchName": "Sir Salimullah Road Dhaka", "Code": 7439},
    {"Sl": 736, "BranchName": "Adabor 16 Uposhakha Dhaka", "Code": 7440},
    {"Sl": 737, "BranchName": "Katasur Uposhakha Dhaka", "Code": 7441},
    {"Sl": 738, "BranchName": "Tajmahal Road Uposhakha Dhaka", "Code": 7442},
    {"Sl": 739, "BranchName": "Noorjahan Road Uposhakha Dhaka", "Code": 7443},
    {"Sl": 740, "BranchName": "Adabor 11 Uposhakha Dhaka", "Code": 7444},
    {"Sl": 741, "BranchName": "West Nakhalpara Uposhakha  Dhaka", "Code": 7455},
    {"Sl": 742, "BranchName": "East Nakhalpara Uposhakha Dhaka", "Code": 7456},
    {"Sl": 743, "BranchName": "Kunipara Happy Homes Dhaka", "Code": 7457},
    {"Sl": 744, "BranchName": "Hemayetpur Uposhakha", "Code": 7475},
    {"Sl": 745, "BranchName": "Maddho Paikpara Uposhakha", "Code": 7476},
    {
      "Sl": 746,
      "BranchName": "Shyamoli Bus Stand Uposhakha  Dhaka",
      "Code": 7477
    },
    {"Sl": 747, "BranchName": "Kallayanpur Uposhakha Dhaka", "Code": 7478},
    {"Sl": 748, "BranchName": "Golartek Uposhakha Dhaka", "Code": 7479},
    {"Sl": 749, "BranchName": "Shahjahan Market Uposhakha Dhaka", "Code": 7480},
    {"Sl": 750, "BranchName": "Kaundia Uposhakha  Dhaka", "Code": 7481},
    {
      "Sl": 751,
      "BranchName": "Boro Bazar Gabtoli Uposhakha  Dhaka",
      "Code": 7482
    },
    {"Sl": 752, "BranchName": "Sarulia Uposhakha", "Code": 7490},
    {"Sl": 753, "BranchName": "Bamuil Uposhakha", "Code": 7491},
    {"Sl": 754, "BranchName": "Sanarpar Uposhakha", "Code": 7492},
    {"Sl": 755, "BranchName": "Kazla Uposhakha  Dhaka", "Code": 7493},
    {"Sl": 756, "BranchName": "Dogair Bazar Uposhakha Dhaka", "Code": 7494},
    {"Sl": 757, "BranchName": "Matuail School Road Upo. Dhaka", "Code": 7495},
    {"Sl": 758, "BranchName": "South Jatrabari Uposhakha Dhaka", "Code": 7496},
    {"Sl": 759, "BranchName": "Wari Uposhakha", "Code": 7505},
    {"Sl": 760, "BranchName": "Karimullahbagh Uposhakha Dhaka", "Code": 7506},
    {"Sl": 761, "BranchName": "Mirhazirbagh Uposhakha Dhaka", "Code": 7507},
    {"Sl": 762, "BranchName": "Mollartek Kosaibari Upo  Dhaka", "Code": 7508},
    {"Sl": 763, "BranchName": "Abdullahpur Bus Stand Uposhakha", "Code": 7515},
    {"Sl": 764, "BranchName": "Fulbaria Bazar Uposhakha  Dhaka", "Code": 7516},
    {"Sl": 765, "BranchName": "Kamarpara Uposhakha  Dhaka", "Code": 7517},
    {"Sl": 766, "BranchName": "Uttarkhan Masterpara Uposhakha", "Code": 7518},
    {
      "Sl": 767,
      "BranchName": "Sector 12 Khalpar Uposhakha Dhaka",
      "Code": 7519
    },
    {"Sl": 768, "BranchName": "Rajabari Chowrasta Upo. Dhaka", "Code": 7520},
    {"Sl": 769, "BranchName": "Madhya Pirerbag Uposhakha", "Code": 7530},
    {"Sl": 770, "BranchName": "Mazar Road Uposhakha", "Code": 7531},
    {"Sl": 771, "BranchName": "Rainkhola Bazar Uposhakha Dhaka", "Code": 7532},
    {"Sl": 772, "BranchName": "Dhan Kheter More Uposhakha Dhaka", "Code": 7533},
    {"Sl": 773, "BranchName": "Tolarbag Uposhakha Dhaka", "Code": 7534},
    {"Sl": 774, "BranchName": "Mirpur 1 Bazar Uposhakha Dhaka", "Code": 7535},
    {"Sl": 775, "BranchName": "Kallayanpur Natun Bazar Dhaka", "Code": 7536},
    {"Sl": 776, "BranchName": "South Banasree Uposhakha", "Code": 7560},
    {"Sl": 777, "BranchName": "Banasree A Block Uposhakha Dhaka", "Code": 7561},
    {"Sl": 778, "BranchName": "Saherunbagh Uposhakha Dhaka", "Code": 7562},
    {"Sl": 779, "BranchName": "Banasree F Block Uposhakha Dhaka", "Code": 7563},
    {"Sl": 780, "BranchName": "Aftabnagar Uposhakha Dhaka", "Code": 7564},
    {"Sl": 781, "BranchName": "Taltola Uposhakha", "Code": 7580},
    {"Sl": 782, "BranchName": "Madartek Uposhakha  Dhaka", "Code": 7581},
    {"Sl": 783, "BranchName": "Nandipara Uposhakha  Dhaka", "Code": 7582},
    {"Sl": 784, "BranchName": "Bashabo Uposhakha  Dhaka", "Code": 7583},
    {"Sl": 785, "BranchName": "North Mugda Uposhakha  Dhaka", "Code": 7584},
    {"Sl": 786, "BranchName": "South Goran Uposhakha  Dhaka", "Code": 7585},
    {"Sl": 787, "BranchName": "Manda Uposhakha Dhaka", "Code": 7586},
    {
      "Sl": 788,
      "BranchName": "Bouddho Mondir Sabujbag Uposhakha",
      "Code": 7587
    },
    {"Sl": 789, "BranchName": "Dakhingaon Bazar Uposhakha Dhaka", "Code": 7588},
    {"Sl": 790, "BranchName": "Holan Bazar  Dakshinkhan  Dhaka", "Code": 7610},
    {"Sl": 791, "BranchName": "Bhaber Char Bazar Munsiganj", "Code": 7620},
    {"Sl": 792, "BranchName": "Baradi Bus Stop Narayanganj", "Code": 7621},
    {"Sl": 793, "BranchName": "Jamaldi Uposhakha Munshiganj", "Code": 7622},
    {
      "Sl": 794,
      "BranchName": "Meghna Ghat Uposhakha Narayanganj",
      "Code": 7623
    },
    {"Sl": 795, "BranchName": "Kashipur Uposhakha  Narayanganj", "Code": 7810},
    {
      "Sl": 796,
      "BranchName": "Tamak Potti Uposhakha Narayanganj",
      "Code": 7811
    },
    {"Sl": 797, "BranchName": "Masdair Uposhakha Narayanganj", "Code": 7812},
    {"Sl": 798, "BranchName": "Trishal Uposhakha  Mymensingh", "Code": 7820},
    {
      "Sl": 799,
      "BranchName": "Shombhuganj Uposhakha  Mymensingh",
      "Code": 7821
    },
    {"Sl": 800, "BranchName": "Natun Bazar Uposhakha Mymensingh", "Code": 7822},
    {"Sl": 801, "BranchName": "Muktagacha Uposhakha Mymensingh", "Code": 7823},
    {"Sl": 802, "BranchName": "Fulpur Uposhakha Mymensingh", "Code": 7824},
    {"Sl": 803, "BranchName": "Tarakanda Uposhakha Mymensingh", "Code": 7825},
    {"Sl": 804, "BranchName": "Purbadhola Uposhakha Netrokona", "Code": 7826},
    {"Sl": 805, "BranchName": "Ishwarganj Uposhakha Mymensingh", "Code": 7827},
    {"Sl": 806, "BranchName": "Shyamgonj Uposhakha Netrokona", "Code": 7828},
    {"Sl": 807, "BranchName": "Telegati Bazar Atpara Netrokona", "Code": 7829},
    {"Sl": 808, "BranchName": "Gafargaon Uposhakha Mymensingh", "Code": 7830},
    {"Sl": 809, "BranchName": "Charpara Uposhakha Mymensingh", "Code": 7831},
    {
      "Sl": 810,
      "BranchName": "Barhatta Bazar Uposhakha Netrokona",
      "Code": 7832
    },
    {"Sl": 811, "BranchName": "Kalmakanda Uposhakha Netrokona", "Code": 7833},
    {"Sl": 812, "BranchName": "Madan Uposhakha Netrokona", "Code": 7834},
    {"Sl": 813, "BranchName": "Gouripur  Mymensingh Mymensingh", "Code": 7835},
    {"Sl": 814, "BranchName": "Haluaghat Uposhakha Mymensingh", "Code": 7836},
    {"Sl": 815, "BranchName": "Kewatkhali Uposhakha Mymensingh", "Code": 7837},
    {"Sl": 816, "BranchName": "Kendua Bazar Uposhakha Netrokona", "Code": 7838},
    {"Sl": 817, "BranchName": "Purbadhala Bazar Upo Netrokona", "Code": 7839},
    {"Sl": 818, "BranchName": "Goalchamot Uposhakha", "Code": 7840},
    {
      "Sl": 819,
      "BranchName": "Tepakhola Bazar Uposhakha Faridpur",
      "Code": 7841
    },
    {
      "Sl": 820,
      "BranchName": "Charbhadrasan Bazar Upo. Faridpur",
      "Code": 7842
    },
    {
      "Sl": 821,
      "BranchName": "Kanaipur Bazar Uposhakha Faridpur",
      "Code": 7843
    },
    {"Sl": 822, "BranchName": "Gozaria Bazar Uposhakha Faridpur", "Code": 7844},
    {
      "Sl": 823,
      "BranchName": "Kholilpur Bazar Uposhakha Faridpur",
      "Code": 7845
    },
    {"Sl": 824, "BranchName": "Hatkrisnapur Uposhakha Faridpur", "Code": 7846},
    {
      "Sl": 825,
      "BranchName": "Sadarpur Bazar Uposhakha Faridpur",
      "Code": 7847
    },
    {"Sl": 826, "BranchName": "Nolia Jamalpur Bazar  Faridpur", "Code": 7848},
    {"Sl": 827, "BranchName": "Boalmari Uposhakha Faridpur", "Code": 7849},
    {"Sl": 828, "BranchName": "Alfadanga Uposhakha Faridpur", "Code": 7850},
    {"Sl": 829, "BranchName": "Satoir Bazar Uposhakha Faridpur", "Code": 7851},
    {
      "Sl": 830,
      "BranchName": "Moyendia Bazar Uposhakha Faridpur",
      "Code": 7852
    },
    {"Sl": 831, "BranchName": "Saltha Bazar Uposhakha Faridpur", "Code": 7853},
    {
      "Sl": 832,
      "BranchName": "Momin Khar Hat Uposhakha Faridpur",
      "Code": 7854
    },
    {"Sl": 833, "BranchName": "Pathrail Uposhakha", "Code": 7855},
    {"Sl": 834, "BranchName": "Bottola Uposhakha Tangail", "Code": 7856},
    {"Sl": 835, "BranchName": "Elenga Uposhakha Tangail", "Code": 7857},
    {"Sl": 836, "BranchName": "Ghatail Uposhakha Tangail", "Code": 7858},
    {"Sl": 837, "BranchName": "Takterchala Uposhakha Tangail", "Code": 7859},
    {"Sl": 838, "BranchName": "Tangail Baby Stand Uposhakha", "Code": 7860},
    {"Sl": 839, "BranchName": "Bhuapur Uposhakha Tangail", "Code": 7861},
    {"Sl": 840, "BranchName": "College Para Uposhakha Tangail", "Code": 7862},
    {"Sl": 841, "BranchName": "Shakhipur Uposhakha Tangail", "Code": 7863},
    {"Sl": 842, "BranchName": "Registry Para Uposhakha Tangail", "Code": 7864},
    {"Sl": 843, "BranchName": "Khanpur Bazar Narayanganj", "Code": 7865},
    {"Sl": 844, "BranchName": "Ajmeribag Tallah Narayanganj", "Code": 7866},
    {"Sl": 845, "BranchName": "Tagarpar Isdair Upo. Narayanganj", "Code": 7867},
    {"Sl": 846, "BranchName": "Narayanganj BB Road Uposhakha", "Code": 7868},
    {
      "Sl": 847,
      "BranchName": "Kalir Bazar Uposhakha Narayanganj",
      "Code": 7869
    },
    {"Sl": 848, "BranchName": "Deobhog Uposhakha Narayanganj", "Code": 7870},
    {"Sl": 849, "BranchName": "Chashara Balur Math Narayanganj", "Code": 7871},
    {"Sl": 850, "BranchName": "Baburail Bazar Upo Narayanganj", "Code": 7872},
    {"Sl": 851, "BranchName": "Damudya Uposhakha Shariatpur", "Code": 7875},
    {"Sl": 852, "BranchName": "Khoajpur Uposhakha Madaripur", "Code": 7876},
    {"Sl": 853, "BranchName": "Ghorishar Uposhakha Shariatpur", "Code": 7877},
    {"Sl": 854, "BranchName": "Vedorganj Uposhakha Shariatpur", "Code": 7878},
    {"Sl": 855, "BranchName": "Zazira Uposhakha Shariatpur", "Code": 7879},
    {
      "Sl": 856,
      "BranchName": "Monohor Bazar Uposhakha Shariatpur",
      "Code": 7880
    },
    {"Sl": 857, "BranchName": "Gosairhat Uposhakha Shariatpur", "Code": 7881},
    {
      "Sl": 858,
      "BranchName": "Sakhipur Shariatpur Upo Shariatpur",
      "Code": 7882
    },
    {
      "Sl": 859,
      "BranchName": "Kaliganj Bazar Uposhakha  Gazipur",
      "Code": 7885
    },
    {"Sl": 860, "BranchName": "Palash Uposhakha  Narsingdi", "Code": 7886},
    {"Sl": 861, "BranchName": "Bashair Bazar Uposhakha Gazipur", "Code": 7887},
    {"Sl": 862, "BranchName": "Charsindur Bazar Upo. Narshingdi", "Code": 7888},
    {"Sl": 863, "BranchName": "Dolan Bazar Uposhakha Gazipur", "Code": 7889},
    {"Sl": 864, "BranchName": "Monohordi Uposhakha", "Code": 7895},
    {"Sl": 865, "BranchName": "Karimpur Uposhakha  Narsingdi", "Code": 7896},
    {
      "Sl": 866,
      "BranchName": "Shibpur Bazar Uposhakha  Narsingdi",
      "Code": 7897
    },
    {"Sl": 867, "BranchName": "Baroicha Uposhakha  Narsingdi", "Code": 7898},
    {"Sl": 868, "BranchName": "Itakhola Uposhakha Narsingdi", "Code": 7899},
    {
      "Sl": 869,
      "BranchName": "Hatirdia Bazar Uposhakha Narsingdi",
      "Code": 7900
    },
    {
      "Sl": 870,
      "BranchName": "Narsingdi Bazar Uposhakha Narsingdi",
      "Code": 7901
    },
    {
      "Sl": 871,
      "BranchName": "Poradia Bazar Uposhakha Narsingdi",
      "Code": 7902
    },
    {"Sl": 872, "BranchName": "Sararchar Uposhakha  Kishoreganj", "Code": 7905},
    {"Sl": 873, "BranchName": "Katiadi Uposhakha Kishoreganj", "Code": 7906},
    {"Sl": 874, "BranchName": "Kuliarchar Uposhakha Kishoreganj", "Code": 7907},
    {"Sl": 875, "BranchName": "Tarail Uposhakha Kishoreganj", "Code": 7908},
    {"Sl": 876, "BranchName": "Nikli Kishoreganj", "Code": 7909},
    {"Sl": 877, "BranchName": "Tongibari Uposhakha  Munshiganj", "Code": 7915},
    {"Sl": 878, "BranchName": "Hatimara Uposhakha  Munshiganj", "Code": 7916},
    {"Sl": 879, "BranchName": "Munshiganj Sadar Munshiganj", "Code": 7917},
    {"Sl": 880, "BranchName": "Baligaon Uposhakha Munshiganj", "Code": 7918},
    {"Sl": 881, "BranchName": "Rikabi Bazar Munshiganj", "Code": 7919},
    {"Sl": 882, "BranchName": "Paschim Mukterpur Upo Munshiganj", "Code": 7920},
    {"Sl": 883, "BranchName": "Banti Bazar Uposhakha", "Code": 7925},
    {
      "Sl": 884,
      "BranchName": "Khoria Bazar Uposhakha Narayanganj",
      "Code": 7926
    },
    {"Sl": 885, "BranchName": "Shekharchar Baburhat Narsingdi", "Code": 7927},
    {"Sl": 886, "BranchName": "Chanpara Bazar Upo. Narayanganj", "Code": 7928},
    {"Sl": 887, "BranchName": "Kashimpur Uposhakha  Gazipur", "Code": 7935},
    {"Sl": 888, "BranchName": "Baimail Uposhakha Gazipur", "Code": 7936},
    {"Sl": 889, "BranchName": "Noser Market Uposhakha Gazipur", "Code": 7937},
    {
      "Sl": 890,
      "BranchName": "Jalirpar Bazar Uposhakha Gopalganj",
      "Code": 7945
    },
    {"Sl": 891, "BranchName": "Kabirajpur Bazar Upo. Madaripur", "Code": 7946},
    {"Sl": 892, "BranchName": "Mostafapur Uposhakha Madaripur", "Code": 7947},
    {"Sl": 893, "BranchName": "Charmuguria Uposhakha Madaripur", "Code": 7948},
    {"Sl": 894, "BranchName": "Bhanga Bazar Uposhakha Faridpur", "Code": 7949},
    {"Sl": 895, "BranchName": "Kalkini Uposhakha Madaripur", "Code": 7950},
    {"Sl": 896, "BranchName": "Shibchar Uposhakha Madaripur", "Code": 7951},
    {"Sl": 897, "BranchName": "Genda Uposhakha", "Code": 7955},
    {"Sl": 898, "BranchName": "Kalma Uposhakha", "Code": 7956},
    {"Sl": 899, "BranchName": "Singair Road Uposhakha Dhaka", "Code": 7957},
    {"Sl": 900, "BranchName": "Kuturia Uposhakha Dhaka", "Code": 7958},
    {
      "Sl": 901,
      "BranchName": "Shahibag Chowrasta Uposhakha Dhaka",
      "Code": 7959
    },
    {
      "Sl": 902,
      "BranchName": "Rajfulbaria Bazar Uposhakha Dhaka",
      "Code": 7960
    },
    {"Sl": 903, "BranchName": "Bank Town Uposhakha Dhaka", "Code": 7961},
    {
      "Sl": 904,
      "BranchName": "Savar Thana Stand Uposhakha Dhaka",
      "Code": 7962
    },
    {"Sl": 905, "BranchName": "Chayabithi Uposhakha Dhaka", "Code": 7963},
    {"Sl": 906, "BranchName": "Pagla Uposhakha Narayanganj", "Code": 7970},
    {"Sl": 907, "BranchName": "Dharmaganj Uposhakha Narayanganj", "Code": 7971},
    {
      "Sl": 908,
      "BranchName": "Muslimnagar Uposhakha Narayanganj",
      "Code": 7972
    },
    {"Sl": 909, "BranchName": "Fatullah Bazar  NARAYANGANJ", "Code": 7973},
    {"Sl": 910, "BranchName": "Aliganj Uposhakha Narayanganj", "Code": 7974},
    {"Sl": 911, "BranchName": "Boktaboli Bazar Upo Narayanganj", "Code": 7975},
    {
      "Sl": 912,
      "BranchName": "BSCIC Fakir Market Uposhaka Gazipur",
      "Code": 7980
    },
    {"Sl": 913, "BranchName": "Mirer Bazar Uposhakha  Gazipur", "Code": 7981},
    {
      "Sl": 914,
      "BranchName": "Station Road Natun Bazar Tongi Gazi",
      "Code": 7982
    },
    {"Sl": 915, "BranchName": "Pubail Bazar Uposhakha Gazipur", "Code": 7983},
    {"Sl": 916, "BranchName": "Pubail Thana Road Upo  Gazipur", "Code": 7984},
    {"Sl": 917, "BranchName": "Galimpur Uposhakha  Dhaka", "Code": 7990},
    {"Sl": 918, "BranchName": "Komorganj Uposhakha Dhaka", "Code": 7991},
    {"Sl": 919, "BranchName": "Paragram Hat Dhaka", "Code": 7992},
    {"Sl": 920, "BranchName": "Bandura Dhaka", "Code": 7993},
    {"Sl": 921, "BranchName": "Baraikhali Bazar Upo Munshiganj", "Code": 7994},
    {"Sl": 922, "BranchName": "Sataish Uposhakha", "Code": 8000},
    {"Sl": 923, "BranchName": "Boro Bari Uposhakha  Gazipur", "Code": 8001},
    {"Sl": 924, "BranchName": "Maleker Bari Uposhakha Gazipur", "Code": 8002},
    {"Sl": 925, "BranchName": "Sign Board Gazipur Uposhakha", "Code": 8003},
    {"Sl": 926, "BranchName": "Nayarhat Bazar Uposhakha", "Code": 8015},
    {"Sl": 927, "BranchName": "Kalampur Uposhakha  Dhaka", "Code": 8016},
    {"Sl": 928, "BranchName": "Saturia Uposhakha Dhaka", "Code": 8017},
    {"Sl": 929, "BranchName": "Khejurbag Uposhakha", "Code": 8025},
    {"Sl": 930, "BranchName": "Chunkutia Uposhakha Dhaka", "Code": 8026},
    {"Sl": 931, "BranchName": "East Chorail Uposhakha Dhaka", "Code": 8027},
    {"Sl": 932, "BranchName": "Doleshwar Uposhakha Dhaka", "Code": 8028},
    {"Sl": 933, "BranchName": "Alukanda Stand Bazar Dhaka", "Code": 8029},
    {"Sl": 934, "BranchName": "Zinzira Uposhakha Dhaka", "Code": 8030},
    {"Sl": 935, "BranchName": "Baipail Uposhakha", "Code": 8035},
    {"Sl": 936, "BranchName": "Zirabo Uposhakha", "Code": 8036},
    {"Sl": 937, "BranchName": "Kathgora Bazar Uposhakha Dhaka", "Code": 8037},
    {"Sl": 938, "BranchName": "Yusuf Market Uposhakha Dhaka", "Code": 8038},
    {"Sl": 939, "BranchName": "Kurgaon Uposhakha Dhaka", "Code": 8039},
    {"Sl": 940, "BranchName": "South Gazirchat Uposhakha Dhaka", "Code": 8040},
    {"Sl": 941, "BranchName": "Ambagan Uposhakha Dhaka", "Code": 8041},
    {"Sl": 942, "BranchName": "Ghoshbag Uposhakha Dhaka", "Code": 8042},
    {"Sl": 943, "BranchName": "Vadail Bazar Uposhakha Dhaka", "Code": 8043},
    {"Sl": 944, "BranchName": "Ashulia Bazar Uposhakha Dhaka", "Code": 8044},
    {"Sl": 945, "BranchName": "Amulia Staff Quarter Uposhakha", "Code": 8045},
    {"Sl": 946, "BranchName": "Modonpur Uposhakha  Narayanganj", "Code": 8046},
    {"Sl": 947, "BranchName": "Bhulta Uposhakha  Narayanganj", "Code": 8047},
    {
      "Sl": 948,
      "BranchName": "Shiddhirganj Uposhakha  Narayanganj",
      "Code": 8048
    },
    {"Sl": 949, "BranchName": "Kanchpur Uposhakha Narayanganj", "Code": 8049},
    {
      "Sl": 950,
      "BranchName": "Godnail Chowdhurybari Narayanganj",
      "Code": 8050
    },
    {"Sl": 951, "BranchName": "Borpa Uposhakha Narayanganj", "Code": 8051},
    {"Sl": 952, "BranchName": "Borabo Bus Stand Narayanganj", "Code": 8052},
    {"Sl": 953, "BranchName": "Chandra Uposhakha", "Code": 8060},
    {"Sl": 954, "BranchName": "Baroipara Uposhakha", "Code": 8061},
    {"Sl": 955, "BranchName": "Chakrabarti Bazar Uposhakha", "Code": 8062},
    {"Sl": 956, "BranchName": "Beximco Industrial Park Gazipur", "Code": 8063},
    {"Sl": 957, "BranchName": "Kaliakoir Uposhakha Gazipur", "Code": 8064},
    {"Sl": 958, "BranchName": "Gorai Uposhakha Tangail", "Code": 8065},
    {"Sl": 959, "BranchName": "Ghior Bazar Uposhakha", "Code": 8070},
    {"Sl": 960, "BranchName": "Baniajuri Bazar Upo. Manikganj", "Code": 8071},
    {"Sl": 961, "BranchName": "Aricha Ghat Uposhakha Manikganj", "Code": 8072},
    {"Sl": 962, "BranchName": "Nali Bazar Uposhakha Manikganj", "Code": 8073},
    {
      "Sl": 963,
      "BranchName": "Charigram Bazar Uposhakha Manikganj",
      "Code": 8074
    },
    {"Sl": 964, "BranchName": "Jamsha Bazar Manikganj", "Code": 8075},
    {"Sl": 965, "BranchName": "Jhitka Bazar Uposhakha Manikganj", "Code": 8076},
    {"Sl": 966, "BranchName": "Golora I/A Uposhakha Manikganj", "Code": 8077},
    {"Sl": 967, "BranchName": "Shreenagar Uposhakha", "Code": 8080},
    {"Sl": 968, "BranchName": "Joypara Uposhakha  Dhaka", "Code": 8081},
    {"Sl": 969, "BranchName": "Vaggyakul Uposhakha Munshigonj", "Code": 8082},
    {
      "Sl": 970,
      "BranchName": "Al Amin Bazar Uposhakha Munshigonj",
      "Code": 8083
    },
    {"Sl": 971, "BranchName": "Fultola Bazar Uposhakha Dhaka", "Code": 8084},
    {"Sl": 972, "BranchName": "Radhaganj Uposhakha", "Code": 8085},
    {
      "Sl": 973,
      "BranchName": "Atosh Ali Bazar Uposhakha Narsingdi",
      "Code": 8086
    },
    {
      "Sl": 974,
      "BranchName": "Raipura Bazar Uposhakha Narsingdi",
      "Code": 8087
    },
    {
      "Sl": 975,
      "BranchName": "Charsubuddi Bazar Upo. Narsingdhi",
      "Code": 8088
    },
    {"Sl": 976, "BranchName": "Abdullahpur Uposhakha", "Code": 8090},
    {"Sl": 977, "BranchName": "Nimtola Uposhakha Munshiganj", "Code": 8091},
    {
      "Sl": 978,
      "BranchName": "Saban Factory More Uposhakha Dhaka",
      "Code": 8092
    },
    {"Sl": 979, "BranchName": "Hasnabad Ekuria", "Code": 8093},
    {"Sl": 980, "BranchName": "Ichapura Bazar  Munshiganj Upo", "Code": 8094},
    {"Sl": 981, "BranchName": "Baluchar Bazar Upo Munshiganj", "Code": 8095},
    {"Sl": 982, "BranchName": "Bhaluka Uposhakha Mymensingh", "Code": 8100},
    {"Sl": 983, "BranchName": "Batajore Bazar Mymenshingh", "Code": 8101},
    {"Sl": 984, "BranchName": "Bogar Bazar Uposhakha Mymenshing", "Code": 8102},
    {"Sl": 985, "BranchName": "Square Masterbari Upo Mymensingh", "Code": 8103},
    {"Sl": 986, "BranchName": "Sona Miah Bazar Narayanganj", "Code": 8110},
    {"Sl": 987, "BranchName": "Hajiganj Wapdar Pool Narayanganj", "Code": 8111},
    {"Sl": 988, "BranchName": "Station Road Fatullah Uposhakha", "Code": 8112},
    {"Sl": 989, "BranchName": "Shimultoli Uposhakha", "Code": 8115},
    {"Sl": 990, "BranchName": "Salna Bazar Uposhakha Gazipur", "Code": 8116},
    {"Sl": 991, "BranchName": "Gorgoria Master Bari  Gazipur", "Code": 8135},
    {"Sl": 992, "BranchName": "Joina Bazar Uposhakha Gazipur", "Code": 8136},
    {"Sl": 993, "BranchName": "Memberbari Uposhakha Gazipur", "Code": 8137},
    {"Sl": 994, "BranchName": "Kaoraid Bazar Uposhakha Gazipur", "Code": 8138},
    {"Sl": 995, "BranchName": "Nakla Uttar Bazar Upo. Sherpur", "Code": 8145},
    {"Sl": 996, "BranchName": "Sreebordi Uposhakha Sherpur", "Code": 8146},
    {"Sl": 997, "BranchName": "Kusumhati Uposhakha Sherpur", "Code": 8147},
    {"Sl": 998, "BranchName": "Jhenaigati Uposhakha Sherpur", "Code": 8148},
    {"Sl": 999, "BranchName": "Nalitabari Uposhakha Sherpur", "Code": 8149},
    {"Sl": 1000, "BranchName": "Nabiganj Uposhakha", "Code": 8155},
    {
      "Sl": 1001,
      "BranchName": "Forazikanda Uposhakha Narayanganj",
      "Code": 8156
    },
    {
      "Sl": 1002,
      "BranchName": "Mongoler Gaon Bottola Bazar Nganj",
      "Code": 8157
    },
    {"Sl": 1003, "BranchName": "Sokal Bazar Uposhakha Jamalpur", "Code": 8165},
    {
      "Sl": 1004,
      "BranchName": "Melandah Bazar Uposhakha Jamalpur",
      "Code": 8166
    },
    {"Sl": 1005, "BranchName": "Balijuri Uposhakha Jamalpur", "Code": 8167},
    {
      "Sl": 1006,
      "BranchName": "Islampur Bazar Jamalpur Uposhakha",
      "Code": 8168
    },
    {
      "Sl": 1007,
      "BranchName": "Char Rajibpur Uposhakha Kurigram",
      "Code": 8169
    },
    {
      "Sl": 1008,
      "BranchName": "Nandina Bazar Uposhakha Jamalpur",
      "Code": 8170
    },
    {
      "Sl": 1009,
      "BranchName": "Hazipur Bazar  Jamalpur Uposhakha",
      "Code": 8171
    },
    {
      "Sl": 1010,
      "BranchName": "Mahmudpur Bazar Jamalpur Uposhakha",
      "Code": 8172
    },
    {"Sl": 1011, "BranchName": "Rowmari Uposhakha Kurigram", "Code": 8173},
    {
      "Sl": 1012,
      "BranchName": "Narundi Bazar Uposhakha Jamalpur",
      "Code": 8174
    },
    {"Sl": 1013, "BranchName": "Khilkhet Uposhakha  Dhaka", "Code": 8175},
    {"Sl": 1014, "BranchName": "Kanchan Uposhakha Narayanganj", "Code": 8176},
    {"Sl": 1015, "BranchName": "Dumni Uposhakha Dhaka", "Code": 8177},
    {
      "Sl": 1016,
      "BranchName": "Rupganj Sub Registry Office  N.Ganj",
      "Code": 8178
    },
    {
      "Sl": 1017,
      "BranchName": "Ulukhola Bazar Uposhakha Gazipur",
      "Code": 8179
    },
    {"Sl": 1018, "BranchName": "Natiapara Bazar Uposhakha", "Code": 8185},
    {"Sl": 1019, "BranchName": "Mirzapur Uposhakha Tangail", "Code": 8186},
    {"Sl": 1020, "BranchName": "Basail Uposhakha Tangail", "Code": 8187},
    {"Sl": 1021, "BranchName": "Sagardighi Uposhakha Tangail", "Code": 8188},
    {"Sl": 1022, "BranchName": "Saheprotap Bazar Uposhakha", "Code": 8195},
    {"Sl": 1023, "BranchName": "Velanagar", "Code": 8196},
    {"Sl": 1024, "BranchName": "Bochila Uposhakha  Dhaka", "Code": 8205},
    {"Sl": 1025, "BranchName": "Ruhitpur Uposhakha Dhaka", "Code": 8206},
    {"Sl": 1026, "BranchName": "Kalatiya Uposhakha Dhaka", "Code": 8207},
    {"Sl": 1027, "BranchName": "Kholamora Uposhakha Dhaka", "Code": 8208},
    {"Sl": 1028, "BranchName": "Jawlahati Chawrasta Upo. Dhaka", "Code": 8209},
    {"Sl": 1029, "BranchName": "Jhawchar Uposhakha Dhaka", "Code": 8210},
    {"Sl": 1030, "BranchName": "Ati Bazar Dhaka", "Code": 8211},
    {"Sl": 1031, "BranchName": "Jhalkuri Uposhakha", "Code": 8215},
    {"Sl": 1032, "BranchName": "Delpara Bazar Uposhakha", "Code": 8216},
    {
      "Sl": 1033,
      "BranchName": "Hirajheel Uposhakha  Narayanganj",
      "Code": 8217
    },
    {
      "Sl": 1034,
      "BranchName": "Sanarpar Rahim Market Road N.ganj",
      "Code": 8218
    },
    {"Sl": 1035, "BranchName": "Signboard Uposhakha Narayanganj", "Code": 8219},
    {"Sl": 1036, "BranchName": "Dattapara Uposhakha Dhaka", "Code": 8225},
    {"Sl": 1037, "BranchName": "Bhadam Bazar Uposhakha Gazipur", "Code": 8226},
    {"Sl": 1038, "BranchName": "Kha Para Road Tongi Gazipur", "Code": 8227},
    {"Sl": 1039, "BranchName": "Bangla Bazar Uposhakha", "Code": 8235},
    {
      "Sl": 1040,
      "BranchName": "Monipur Bazar Uposhakha Joydebpur",
      "Code": 8236
    },
    {"Sl": 1041, "BranchName": "Rajendrapur Gazipur", "Code": 8237},
    {
      "Sl": 1042,
      "BranchName": "Jamalpur Chowrasta Bazar  Gazipur",
      "Code": 8238
    },
    {"Sl": 1043, "BranchName": "Lohagachhia Bazar Gazipur", "Code": 8239},
    {
      "Sl": 1044,
      "BranchName": "Fulbaria Bazar Kaliakoir  Gazipur",
      "Code": 8240
    },
    {"Sl": 1045, "BranchName": "Amraid Bazar Uposhakha  Gazipur", "Code": 8245},
    {
      "Sl": 1046,
      "BranchName": "Raniganj Bazar Uposhakha  Gazipur",
      "Code": 8246
    },
    {"Sl": 1047, "BranchName": "Targaon Uposhakha Gazipur", "Code": 8247},
    {
      "Sl": 1048,
      "BranchName": "Toke Nayon Bazar Uposhakha Gazipur",
      "Code": 8248
    },
    {
      "Sl": 1049,
      "BranchName": "Vannara Bazar Uposhakha  Gazipur",
      "Code": 8255
    },
    {"Sl": 1050, "BranchName": "Ansar Academy Uposhakha Gazipur", "Code": 8256},
    {
      "Sl": 1051,
      "BranchName": "Jamtola Mouchak Uposhakha Gazipur",
      "Code": 8257
    },
    {
      "Sl": 1052,
      "BranchName": "Goalanda Moor Uposhakha  Rajbari",
      "Code": 8265
    },
    {"Sl": 1053, "BranchName": "Rajbari Uposhakha Rajbari", "Code": 8266},
    {
      "Sl": 1054,
      "BranchName": "Maishala Bazar Pangsha Upo Rajbari",
      "Code": 8267
    },
    {"Sl": 1055, "BranchName": "Machpara Uposhakha Rajbari", "Code": 8268},
    {"Sl": 1056, "BranchName": "Kolar Hat Uposhakha Rajbari", "Code": 8269},
    {
      "Sl": 1057,
      "BranchName": "Rotondia Bazar Kalukhali Rajbari",
      "Code": 8270
    },
    {"Sl": 1058, "BranchName": "Sonapur Bazar Uposhakha Rajbari", "Code": 8271},
    {"Sl": 1059, "BranchName": "Narua Bazar Uposhakha  Rajbari", "Code": 8272},
    {"Sl": 1060, "BranchName": "Nandail Uposhakha Mymensingh", "Code": 8275},
    {"Sl": 1061, "BranchName": "Karimganj Uposhakha Kishoreganj", "Code": 8276},
    {"Sl": 1062, "BranchName": "Pakundia Upo. Kishoreganj", "Code": 8277},
    {
      "Sl": 1063,
      "BranchName": "Boro Bazar Kishoreganj Uposhakha",
      "Code": 8278
    },
    {
      "Sl": 1064,
      "BranchName": "Hossainpur Uposhakha Kishoreganj",
      "Code": 8279
    },
    {"Sl": 1065, "BranchName": "Puler Ghat Bazar Uposhakha", "Code": 8280},
    {"Sl": 1066, "BranchName": "Atharabari Raybazar Mymensingh", "Code": 8281},
    {"Sl": 1067, "BranchName": "Dhuptara Kalibari Narayanganj", "Code": 8285},
    {
      "Sl": 1068,
      "BranchName": "Sonargaon Taltola Bazar Narayanganj",
      "Code": 8286
    },
    {
      "Sl": 1069,
      "BranchName": "Madhukhali Bazar Uposhakha Faridpur",
      "Code": 8290
    },
    {"Sl": 1070, "BranchName": "Char Hajiganj Faridpur Faridpur", "Code": 8291},
    {"Sl": 1071, "BranchName": "Baliakandi Rajbari Uposhakha", "Code": 8292},
    {"Sl": 1072, "BranchName": "Kotalipara Uposhakha Gopalganj", "Code": 8293},
    {"Sl": 1073, "BranchName": "Nagarkanda Uposhakha  Faridpur", "Code": 8294},
    {"Sl": 1074, "BranchName": "Madhupur Uposhakha Tangail", "Code": 8295},
    {
      "Sl": 1075,
      "BranchName": "Jamtoli Bazar Jamalpur Uposhakha",
      "Code": 8296
    },
    {"Sl": 1076, "BranchName": "Tarakandi Uposhakha Jamalpur", "Code": 8297},
    {
      "Sl": 1077,
      "BranchName": "Kalibari BusStand Gabtoli Mymensing",
      "Code": 8298
    },
    {
      "Sl": 1078,
      "BranchName": "Aramnagar Bazar Sarisabari Jamalpur",
      "Code": 8299
    },
    {"Sl": 1079, "BranchName": "Koyra Bazar Uposhakha Jamalpur", "Code": 8300},
    {
      "Sl": 1080,
      "BranchName": "Barachaona Bazar Uposhakha Tangail",
      "Code": 8305
    },
    {"Sl": 1081, "BranchName": "Gopalpur Uposhakha Tangail", "Code": 8306},
    {
      "Sl": 1082,
      "BranchName": "Kasturipara Bazar Uposhakha Tangail",
      "Code": 8307
    },
    {"Sl": 1083, "BranchName": "Kalihati Uposhakha Tangail", "Code": 8308},
    {"Sl": 1084, "BranchName": "Balla Uposhakha Tangail", "Code": 8309},
    {
      "Sl": 1085,
      "BranchName": "Nagarpur Tangail Uposhakha Tangail",
      "Code": 8310
    },
    {"Sl": 1086, "BranchName": "Garo Bazar Uposhakha Tangail", "Code": 8311},
    {"Sl": 1087, "BranchName": "Parkhi Bazar Uposhakha Tangail", "Code": 8312},
    {"Sl": 1088, "BranchName": "Nalua Tangail", "Code": 8313},
    {"Sl": 1089, "BranchName": "Palli Bidyut Ashulia Dhaka", "Code": 8315},
    {"Sl": 1090, "BranchName": "Dobli Bazar Uposhakha Dhaka", "Code": 8335},
    {"Sl": 1091, "BranchName": "Dohar Bazar Uposhakha Dhaka", "Code": 8336},
    {
      "Sl": 1092,
      "BranchName": "Muksudpur Gopalganj Upo Gopalganj",
      "Code": 8340
    },
    {"Sl": 1093, "BranchName": "Tungipara Uposhakha Gopalganj", "Code": 8341},
    {"Sl": 1094, "BranchName": "Kurpar Uposhakha  Netrokona", "Code": 8350},
    {"Sl": 1095, "BranchName": "Durgapur Netrokona Uposhakha", "Code": 8351},
    {"Sl": 1096, "BranchName": "Kamarkhali Uposhakha  Faridpur", "Code": 8380},
    {"Sl": 1097, "BranchName": "Racecourse Uposhakha", "Code": 8500},
    {"Sl": 1098, "BranchName": "Paaduar Bazar Uposhakha", "Code": 8501},
    {"Sl": 1099, "BranchName": "Burichang Uposhakha  Cumilla", "Code": 8502},
    {
      "Sl": 1100,
      "BranchName": "Baghmara Bazar Uposhakha  Cumilla",
      "Code": 8503
    },
    {"Sl": 1101, "BranchName": "Kotbari Uposhakha Cumilla", "Code": 8504},
    {"Sl": 1102, "BranchName": "Cumilla EPZ Uposhakha Cumilla", "Code": 8505},
    {"Sl": 1103, "BranchName": "Ranir Bazar Uposhakha Cumilla", "Code": 8506},
    {"Sl": 1104, "BranchName": "Kandirpar Uposhakha Cumilla", "Code": 8507},
    {
      "Sl": 1105,
      "BranchName": "Bipulashar Bazar Uposhakha Cumilla",
      "Code": 8508
    },
    {
      "Sl": 1106,
      "BranchName": "Lakshmanpur Bazar Uposhakha Cumilla",
      "Code": 8509
    },
    {"Sl": 1107, "BranchName": "Bizra Bazar Uposhakha Cumilla", "Code": 8510},
    {
      "Sl": 1108,
      "BranchName": "Sankuchail Bazar Uposhakha Cumilla",
      "Code": 8511
    },
    {"Sl": 1109, "BranchName": "Nangalkot Uposhakha Cumilla", "Code": 8512},
    {"Sl": 1110, "BranchName": "Manoharganj Uposhakha Cumilla", "Code": 8513},
    {
      "Sl": 1111,
      "BranchName": "Brahmanpara Bazar Uposhakha Cumilla",
      "Code": 8514
    },
    {"Sl": 1112, "BranchName": "Natherpetua Uposhakha Cumilla", "Code": 8515},
    {"Sl": 1113, "BranchName": "Muddafarganj Uposhakha Cumilla", "Code": 8516},
    {"Sl": 1114, "BranchName": "Jafarganj Uposhakha Cumilla", "Code": 8517},
    {"Sl": 1115, "BranchName": "Bholain Bazar Uposhakha Cumilla", "Code": 8518},
    {"Sl": 1116, "BranchName": "Balutupa Bazar Cumilla", "Code": 8519},
    {"Sl": 1117, "BranchName": "Academy Road Uposhakha", "Code": 8520},
    {"Sl": 1118, "BranchName": "Chagalnaiya Uposhakha Feni", "Code": 8521},
    {"Sl": 1119, "BranchName": "Fulgazi Uposhakha Feni", "Code": 8522},
    {"Sl": 1120, "BranchName": "Hajir Bazar Uposhakha Feni", "Code": 8523},
    {
      "Sl": 1121,
      "BranchName": "Baraiyarhat Uposhakha Chattogram",
      "Code": 8524
    },
    {"Sl": 1122, "BranchName": "Dorbesher Hat Uposhakha Feni", "Code": 8525},
    {"Sl": 1123, "BranchName": "Parshuram Uposhakha Feni", "Code": 8526},
    {"Sl": 1124, "BranchName": "Boktar Munshir Bazar  Feni", "Code": 8527},
    {"Sl": 1125, "BranchName": "Laskarhat Uposhakha Feni", "Code": 8528},
    {"Sl": 1126, "BranchName": "Maijdee Uposhakha", "Code": 8535},
    {"Sl": 1127, "BranchName": "Basurhat Uposhakha  Noakhali", "Code": 8536},
    {"Sl": 1128, "BranchName": "Amishapara Uposhakha  Noakhali", "Code": 8537},
    {
      "Sl": 1129,
      "BranchName": "Sonaimuri BazarUposhakha Noakhali",
      "Code": 8538
    },
    {"Sl": 1130, "BranchName": "Chatkhil Uposhakha Noakhali", "Code": 8539},
    {"Sl": 1131, "BranchName": "Kabirhat Uposhakha Noakhali", "Code": 8540},
    {
      "Sl": 1132,
      "BranchName": "Maijdee Bazar Uposhakha Noakhali",
      "Code": 8541
    },
    {"Sl": 1133, "BranchName": "Chaterpaiya Uposhakha Noakhali", "Code": 8542},
    {"Sl": 1134, "BranchName": "Sonapur Uposhakha Noakhali", "Code": 8543},
    {"Sl": 1135, "BranchName": "Subarnachar Uposhakha Noakhali", "Code": 8544},
    {"Sl": 1136, "BranchName": "Bozra Bazar Uposhakha Noakhali", "Code": 8545},
    {"Sl": 1137, "BranchName": "Senbag Bazar Uposhakha Noakhali", "Code": 8546},
    {"Sl": 1138, "BranchName": "Chaprashir Hat Noakhali", "Code": 8547},
    {"Sl": 1139, "BranchName": "Somir Munshir Hat Noakhali", "Code": 8548},
    {"Sl": 1140, "BranchName": "Chowdhury Hat Noakhali", "Code": 8549},
    {"Sl": 1141, "BranchName": "Debidwar Uposhakha", "Code": 8550},
    {"Sl": 1142, "BranchName": "Bakhrabad Uposhakha  Cumilla", "Code": 8551},
    {"Sl": 1143, "BranchName": "Ramchandrapur Bazar Cumilla", "Code": 8552},
    {
      "Sl": 1144,
      "BranchName": "Bangora BazarUposhakha Brahmanbaria",
      "Code": 8553
    },
    {"Sl": 1145, "BranchName": "Muradnagar Uposhakha Cumilla", "Code": 8554},
    {
      "Sl": 1146,
      "BranchName": "Dakshin Bangora Rupbabu Bazar Upo",
      "Code": 8555
    },
    {
      "Sl": 1147,
      "BranchName": "Mohonpur Bazar Uposhakha Cumilla",
      "Code": 8560
    },
    {"Sl": 1148, "BranchName": "Ram Mohan Uposhakha Cumilla", "Code": 8561},
    {"Sl": 1149, "BranchName": "Badarpur Uposhakha Cumilla", "Code": 8562},
    {"Sl": 1150, "BranchName": "Adda Bazar Uposhakha Cumilla", "Code": 8563},
    {"Sl": 1151, "BranchName": "Barura Uposhakha Cumilla", "Code": 8564},
    {
      "Sl": 1152,
      "BranchName": "Madhaiya Bazar Uposhakha Cumilla",
      "Code": 8565
    },
    {"Sl": 1153, "BranchName": "Mohichail Cumilla", "Code": 8566},
    {"Sl": 1154, "BranchName": "Homna Bazar Uposhakha", "Code": 8570},
    {"Sl": 1155, "BranchName": "Daudkandi Uposhakha Cumilla", "Code": 8571},
    {
      "Sl": 1156,
      "BranchName": "Batakandi Bazar Uposhakha Cumilla",
      "Code": 8572
    },
    {"Sl": 1157, "BranchName": "Ramkrishnopur Uposhakha Cumilla", "Code": 8573},
    {"Sl": 1158, "BranchName": "Eliotganj Uposhakha Cumilla", "Code": 8574},
    {"Sl": 1159, "BranchName": "Nayergaon Uposhakha Chandpur", "Code": 8575},
    {
      "Sl": 1160,
      "BranchName": "Bancharampur Uposhakha Brahmanbaria",
      "Code": 8576
    },
    {
      "Sl": 1161,
      "BranchName": "Narayanpur Bazar Uposhakha Chandpur",
      "Code": 8577
    },
    {"Sl": 1162, "BranchName": "Gouripur Bus Stand Cumilla", "Code": 8578},
    {
      "Sl": 1163,
      "BranchName": "Manikerchar Bazar Uposhakha Cumilla",
      "Code": 8579
    },
    {"Sl": 1164, "BranchName": "Chengarchar Chandpur", "Code": 8580},
    {"Sl": 1165, "BranchName": "Suagonj Bazar Uposhakha", "Code": 8585},
    {"Sl": 1166, "BranchName": "Kashinagar Uposhakha", "Code": 8586},
    {"Sl": 1167, "BranchName": "Nalghar Uposhakha", "Code": 8587},
    {"Sl": 1168, "BranchName": "Buschi Bazar Uposhakha Cumilla", "Code": 8588},
    {"Sl": 1169, "BranchName": "Dhorkora Uposhakha Cumilla", "Code": 8589},
    {"Sl": 1170, "BranchName": "Munshir Hat Uposhakha Cumilla", "Code": 8590},
    {
      "Sl": 1171,
      "BranchName": "Bangodda Bazar Uposhakha Cumilla",
      "Code": 8591
    },
    {"Sl": 1172, "BranchName": "Gunabati Uposhakha  Cumilla", "Code": 8592},
    {"Sl": 1173, "BranchName": "Chauddagram Uposhakha  Cumilla", "Code": 8593},
    {
      "Sl": 1174,
      "BranchName": "Chhayani Bazar Uposhakha Noakhali",
      "Code": 8600
    },
    {"Sl": 1175, "BranchName": "Raipur Uposhakha Lakshmipur", "Code": 8601},
    {
      "Sl": 1176,
      "BranchName": "Dattapara Bazar Laxmipur Uposhakha",
      "Code": 8602
    },
    {
      "Sl": 1177,
      "BranchName": "Khilpara Bazar Uposhakha Noakhali",
      "Code": 8603
    },
    {"Sl": 1178, "BranchName": "Kachua Bazar Uposhakha", "Code": 8610},
    {"Sl": 1179, "BranchName": "Hajiganj Bazar Uposhakha", "Code": 8611},
    {
      "Sl": 1180,
      "BranchName": "Sachar Bazar Uposhakha  Chandpur",
      "Code": 8612
    },
    {"Sl": 1181, "BranchName": "Shahrasti Uposhakha  Chandpur", "Code": 8613},
    {
      "Sl": 1182,
      "BranchName": "Haimchar Bazar Uposhakha Chandpur",
      "Code": 8614
    },
    {"Sl": 1183, "BranchName": "Rahima Nagar Uposhakha Chandpur", "Code": 8615},
    {
      "Sl": 1184,
      "BranchName": "Chandpur Puran Bazar Upo. Chandpur",
      "Code": 8616
    },
    {"Sl": 1185, "BranchName": "Nawabpur Cumilla", "Code": 8617},
    {
      "Sl": 1186,
      "BranchName": "Matlab Dakshin Uposhakha Chandpur",
      "Code": 8618
    },
    {"Sl": 1187, "BranchName": "Chandpur Baburhat Uposhakha ", "Code": 8619},
    {"Sl": 1188, "BranchName": "Nimsar Bazar Uposhakha Cumilla", "Code": 8620},
    {"Sl": 1189, "BranchName": "Kalir Bazar Cumilla Cumilla", "Code": 8621},
    {"Sl": 1190, "BranchName": "Kangshanagar Uposhakha Cumilla", "Code": 8622},
    {"Sl": 1191, "BranchName": "Alekhar Char Uposhakha Cumilla", "Code": 8623},
    {"Sl": 1192, "BranchName": "Bangla Bazar Uposhakha Cumilla", "Code": 8624},
    {"Sl": 1193, "BranchName": "Dalal Bazar Laxmipur Laxmipur", "Code": 8635},
    {"Sl": 1194, "BranchName": "Haiderganj Uposhakha Laxmipur", "Code": 8636},
    {
      "Sl": 1195,
      "BranchName": "Mandari Bazar Uposhakha Laxmipur",
      "Code": 8637
    },
    {
      "Sl": 1196,
      "BranchName": "Rakhalia Bazar Uposhakha Laxmipur",
      "Code": 8638
    },
    {"Sl": 1197, "BranchName": "Ramganj Laxmipur Upo Laxmipur", "Code": 8639},
    {
      "Sl": 1198,
      "BranchName": "Chitoshi Bazar Uposhakha Chandpur",
      "Code": 8645
    },
    {
      "Sl": 1199,
      "BranchName": "Hasanpur Dhalua Road Upo Cumilla",
      "Code": 8646
    },
    {
      "Sl": 1200,
      "BranchName": "Laksham Junction Station Road Upo",
      "Code": 8647
    },
    {"Sl": 1201, "BranchName": "Ananda Bazar Chandpur Uposhakha", "Code": 8655},
    {"Sl": 1202, "BranchName": "Faridganj Uposhakha Chandpur", "Code": 8656},
    {
      "Sl": 1203,
      "BranchName": "Sujatpur Bazar Uposhakha Chandpur",
      "Code": 8657
    },
    {
      "Sl": 1204,
      "BranchName": "Meher Kalibari Uposhakha Chandpur",
      "Code": 8658
    },
    {"Sl": 1205, "BranchName": "Bakila Bazar Uposhakha Chandpur", "Code": 8659},
    {
      "Sl": 1206,
      "BranchName": "Chandra Bazar Uposhakha Chandpur",
      "Code": 8660
    },
    {"Sl": 1207, "BranchName": "Palakhal Uposhakha  Chandpur", "Code": 8662},
    {"Sl": 1208, "BranchName": "Dotter Hat Uposhakha Noakhali", "Code": 8665},
    {"Sl": 1209, "BranchName": "Sebarhat Noakhali", "Code": 8666},
    {"Sl": 1210, "BranchName": "Shantir Hat Uposhakha Noakhali", "Code": 8667},
    {
      "Sl": 1211,
      "BranchName": "Uday Sadhur Hat Uposhakha Noakhali",
      "Code": 8668
    },
    {"Sl": 1212, "BranchName": "Dagonbhuiyan Uposhakha Feni", "Code": 8669},
    {
      "Sl": 1213,
      "BranchName": "Musapur Banglabazar upo  Noakhali",
      "Code": 8670
    },
    {"Sl": 1214, "BranchName": "Jamiderhat Uposhakha Noakhali", "Code": 8672},
    {
      "Sl": 1215,
      "BranchName": "Rahattar Pool Uposhakha  Chattogram",
      "Code": 8765
    },
    {
      "Sl": 1216,
      "BranchName": "Patharghata Uposhakha Chattogram",
      "Code": 8766
    },
    {
      "Sl": 1217,
      "BranchName": "Korbaniganj Uposhakha Chattogram",
      "Code": 8767
    },
    {"Sl": 1218, "BranchName": "Laldighi Uposhakha Chattogram", "Code": 8768},
    {"Sl": 1219, "BranchName": "Chaktai Uposhakha  Chattogram", "Code": 8769},
    {
      "Sl": 1220,
      "BranchName": "Dewan Bazar Uposhakha  Chattogram",
      "Code": 8780
    },
    {"Sl": 1221, "BranchName": "Teri Bazar Uposhakha Chattogram", "Code": 8781},
    {"Sl": 1222, "BranchName": "Kanungopara Chattogram", "Code": 8782},
    {"Sl": 1223, "BranchName": "Munsef Bazar Chattogram", "Code": 8783},
    {"Sl": 1224, "BranchName": "Mohammadpur Ismail Colony CTG", "Code": 8790},
    {"Sl": 1225, "BranchName": "Puratan Chandgaon Uposhakha CTG", "Code": 8791},
    {
      "Sl": 1226,
      "BranchName": "B.Ed College Gate Upo. Chattogram",
      "Code": 8792
    },
    {"Sl": 1227, "BranchName": "Panchlaish Uposhakha Chattogram", "Code": 8793},
    {"Sl": 1228, "BranchName": "Sadarghat Road Uposhakha  CTG", "Code": 8800},
    {"Sl": 1229, "BranchName": "Madarbari Uposhakha Chattogram", "Code": 8801},
    {"Sl": 1230, "BranchName": "Bou Bazar Uposhakha Chattagram", "Code": 8802},
    {
      "Sl": 1231,
      "BranchName": "Enayet Bazar Uposhakha Chattogram",
      "Code": 8803
    },
    {"Sl": 1232, "BranchName": "Jamal Khan Road Chattogram", "Code": 8804},
    {"Sl": 1233, "BranchName": "Kadamtoli Chattogram Uposhakha", "Code": 8810},
    {"Sl": 1234, "BranchName": "P. C. Road Uposhakha Chattogram", "Code": 8811},
    {
      "Sl": 1235,
      "BranchName": "Agrabad Access Road Upo Chattogram",
      "Code": 8812
    },
    {"Sl": 1236, "BranchName": "Dewanhat Uposhakha Chattogram", "Code": 8813},
    {"Sl": 1237, "BranchName": "Pahartoli Uposhakha Chattagram", "Code": 8814},
    {"Sl": 1238, "BranchName": "WASA More Uposhakha  Chattogram", "Code": 8820},
    {"Sl": 1239, "BranchName": "Kala Miah Bazar Uposhakha  CTG", "Code": 8821},
    {"Sl": 1240, "BranchName": "Kunjachaya Uposhakha Chottogram", "Code": 8822},
    {"Sl": 1241, "BranchName": "2 No. Gate Chattogram Uposhakha", "Code": 8823},
    {"Sl": 1242, "BranchName": "Halishahor Uposhakha", "Code": 8835},
    {
      "Sl": 1243,
      "BranchName": "Naya Bazar Uposhakha  Chattogram",
      "Code": 8836
    },
    {"Sl": 1244, "BranchName": "Foillatali Bazar Uposhakha Ctg.", "Code": 8837},
    {
      "Sl": 1245,
      "BranchName": "Artillery Road Uposhakha Chattogram",
      "Code": 8838
    },
    {
      "Sl": 1246,
      "BranchName": "Koibulladham Uposhakha Chattogram",
      "Code": 8839
    },
    {"Sl": 1247, "BranchName": "Airport Road Uposhakha", "Code": 8845},
    {"Sl": 1248, "BranchName": "Steel Mill Uposhakha Chattogram", "Code": 8846},
    {"Sl": 1249, "BranchName": "CEPZ Uposhakha Chattagram", "Code": 8847},
    {
      "Sl": 1250,
      "BranchName": "Aturar Depot Uposhakha Chattogram",
      "Code": 8860
    },
    {"Sl": 1251, "BranchName": "Khaja Road Uposhakha Chattogram", "Code": 8861},
    {
      "Sl": 1252,
      "BranchName": "Chandgaon R/A Uposhakha Chattogram",
      "Code": 8862
    },
    {"Sl": 1253, "BranchName": "Bayazid Uposhakha Chattogram", "Code": 8863},
    {
      "Sl": 1254,
      "BranchName": "Bahaddarhat Uposhakha  Chattogram",
      "Code": 8864
    },
    {"Sl": 1255, "BranchName": "Head Office", "Code": 9900}
  ];
}
